package requirementGroup.Reports;

import static org.junit.Assert.assertTrue;
import static org.testng.Assert.assertEquals;
import java.io.File;
import java.util.Properties;
import lib.dataObject.Login_data;
import lib.dataObject.Report_data;
import lib.dataObject.ResourceType_data;
import lib.dataObject.Resource_data;
import lib.dataObject.Roles_data;
import lib.dataObject.StatusTypes_data;
import lib.dataObject.User_data;
import lib.dataObject.View_data;
import lib.module.NavigationToSubMenus;
import lib.page.AutoIT;
import lib.page.Login;
import lib.page.Map;
import lib.page.RegionDefault;
import lib.page.Regions;
import lib.page.Report;
import lib.page.Resource;
import lib.page.ResourceType;
import lib.page.Roles;
import lib.page.SelectRegion;
import lib.page.StatusTypeList;
import lib.page.UpdateStatus;
import lib.page.UsersList;
import org.testng.annotations.Test;
import qaframework.lib.UserDefinedFunctions.Date_Time_settings;
import qaframework.lib.UserDefinedFunctions.OfficeCommonFunctions;
import qaframework.lib.UserDefinedFunctions.PathsProperties;
import qaframework.lib.UserDefinedFunctions.ReadAutoItProperty;
import qaframework.lib.testngExtensions.TestNG_UI_EXTENSIONS;

public class NewStatewideResourceDetailsReport extends TestNG_UI_EXTENSIONS {

	public NewStatewideResourceDetailsReport() throws Exception {
		super();
		// TODO Auto-generated constructor stub
	}
	
	/********************************************************************************************
	'Description : Verify that RegAdmin cannot generate statewide resource detail report in any 
	               other region apart from 'Statewide Florida'. 
	'Date	 	 : 28-Jul-2015
	'Author		 : Renushree
	'--------------------------------------------------------------------------------------------
	'Modified Date			                        	Modified By
	'Date					                            Name
	**********************************************************************************************/
	@Test(description = "Verify that RegAdmin cannot generate statewide resource detail report in"
			+ " any other region apart from 'Statewide Florida'. ")
	public void testHappyDay99104() throws Exception {

		gstrTCID = "99104";
		gstrTO = "Verify that RegAdmin cannot generate statewide resource detail report in any"
				+ " other region apart from 'Statewide Florida'. ";

		Login_data objTest_data = new Login_data();
		Login objLogin = new Login(this.driver1);
		SelectRegion objSelectRegion = new SelectRegion(this.driver1);
		RegionDefault objRegionDefault = new RegionDefault(this.driver1);
		NavigationToSubMenus objNavigationToSubMenus = new NavigationToSubMenus(
				this.driver1);
		Report objReport = new Report(this.driver1);

		objLogin.loginToApplication(objTest_data.strUserName,
				objTest_data.strPassword);

		objRegionDefault.selectFrame();
		
		String strRegName = objTest_data.strRegionName;
		if (strRegName.equals(objTest_data.strRegionStatewideFlorida)) {
			strRegName = objTest_data.strRegionName1;
		}
		objSelectRegion.selectRegionAndNavigate(objTest_data.strRegionName);

		objRegionDefault.selectFrame();

		objNavigationToSubMenus.clickOnResourceReports();

		objReport.verStatewideResourceDetailsNotDisplayed();

		objLogin.clickLogOut();
		
		gstrResult = "PASS";
	}
		
	/********************************************************************************************************
	'Description : Verify that 'Statewide Resource Details' report can be generated by RegAdmin in 'Statewide
	               Florida' for all the resources for the selected criteria while generating report. 
	'Date	 	 : 15-Sep-2014
	'Author		 : Anil
	'--------------------------------------------------------------------------------------------------------
	'Modified Date			                        	Modified By
	'Date					                            Name
	*********************************************************************************************************/
	@Test(description = "Verify that 'Statewide Resource Details' report can be generated by RegAdmin in 'Statewide Florida' for all the resources for the selected criteria while generating report. ")
	public void testHappyDay99028() throws Exception {

		gstrTCID = "99028";
		gstrTO = "Verify that 'Statewide Resource Details' report can be generated by RegAdmin in 'Statewide Florida' for all the resources for the selected criteria while generating report. ";

		Login_data objLogin_data = new Login_data();
		ResourceType_data objResourceType_data = new ResourceType_data();
		Resource_data objResource_data = new Resource_data();
		StatusTypes_data objStatuTypes_data = new StatusTypes_data();
		Report_data objReport_data = new Report_data();
		PathsProperties objAP = new PathsProperties();
		Properties pathProps = objAP.ReadAutoit_FilePath();
		Date_Time_settings dts = new Date_Time_settings();
		OfficeCommonFunctions objOffCommonFunc = new OfficeCommonFunctions();

		String strTimeText = dts.getCurrentDate(objReport_data.dateFormat1);
		String fileType = objReport_data.reportFile;
		NavigationToSubMenus objNavigationToSubMenus = new NavigationToSubMenus(
				this.driver1);
		Login objLogin = new Login(this.driver1);
		SelectRegion objSelectRegion = new SelectRegion(this.driver1);
		RegionDefault objRegionDefault = new RegionDefault(this.driver1);
		StatusTypeList objStatusTypeList = new StatusTypeList(this.driver1);
		ResourceType objResourceType = new ResourceType(this.driver1);
		Resource objResource = new Resource(this.driver1);
		Regions objRegions_page = new Regions(this.driver1);
		NavigationToSubMenus objNavigationToSubmenus = new NavigationToSubMenus(
				this.driver1);

		AutoIT objAutoIT = new AutoIT(this.driver1);
		Report objReport1 = new Report(this.driver1);
		NavigationToSubMenus objNavigationToSubMenus1 = new NavigationToSubMenus(
				this.driver1);
		Login objLogin1 = new Login(this.driver1);
		SelectRegion objSelectRegion1 = new SelectRegion(this.driver1);
		RegionDefault objRegionDefault1 = new RegionDefault(this.driver1);

		String strstatusTypeValues[] = new String[1];
		String strStdStatusValue[] = new String[1];
		String strStdResourceValue[] = new String[1];
		String strResourceTypeValue[] = new String[1];
		String strRegionValue[] = new String[2];

		String strstatusTypeValuesInReg2[] = new String[1];
		String strStdStatusValueInReg2[] = new String[1];
		String strResourceTypeValueInReg2[] = new String[1];
		String strStdResourceValueInReg2[] = new String[1];

		String AutoIT_FILE_PATH = objReport_data.reportsDownloadAutoItPath;
		String strAutoItPath = ReadAutoItProperty
				.readDataFromAutoItPath(AutoIT_FILE_PATH);
		String strAutoITName = pathProps
				.getProperty(objReport_data.reportsDownloadAutoItName);
		String fileDownloadPath = pathProps
				.getProperty(objReport_data.reportsDownloadPath);

		String autoItFilesPath = pathProps
				.getProperty(objReport_data.autoItPath);

		File file = new File(System.getProperty("user.dir") + fileDownloadPath);

		File autoItFiles = new File(System.getProperty("user.dir")
				+ autoItFilesPath);

		String strDownloadName = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + fileType;
		String strCSVFileNameRenamed = "TC" + gstrTCID + "_" + strTimeText;

		String strCSVDownlRenamedPath = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + objReport_data.xlsFile;

		String strDownloadName1 = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + objReport_data.xlsFile;

		String filePath = file + "\\";

		objLogin.loginToApplication(objLogin_data.strUserName,
				objLogin_data.strPassword);

		objSelectRegion.selectRegionAndNavigate(objLogin_data.strRegionStatewideFlorida);

		objRegionDefault.selectFrame();

		objNavigationToSubMenus.navigateToRegions();

		strRegionValue[0] = objRegions_page
				.getRegionValue(objLogin_data.strRegionStatewideFlorida);

		strRegionValue[1] = objRegions_page
				.getRegionValue(objLogin_data.strRegionName4);

		objNavigationToSubmenus.navigateToStatusTypesInSetup();

		// RoleBased Status Types in Region1
		objStatusTypeList
				.clickCreateNewStatusTypeButton()
				.selectStatusType(objStatuTypes_data.strNumberStatusType)
				.clickNextButton()
				.enterStatusTypeName(objStatuTypes_data.strNSTStatusTypeName)
				.enterStatusTypeDescription(
						objStatuTypes_data.strStatusDescription)
				.selectStandardStatusTypename(
						objStatuTypes_data.strStandardStatusTypename);

		strStdStatusValue[0] = objStatusTypeList
				.getStandardStatusValue(objStatuTypes_data.strStandardStatusTypename);

		System.out.println(strStdStatusValue[0]);

		objStatusTypeList.clickOnSaveButton();

		strstatusTypeValues[0] = objStatusTypeList
				.getStatusValue(objStatuTypes_data.strNSTStatusTypeName);

		// Resource type creation in Region1
		objResourceType.navigateToResourceTypePage().createResourceType(
				objResourceType_data.strResourceTypeName, strstatusTypeValues);

		strResourceTypeValue[0] = objResourceType
				.getResourceTypeValue(objResourceType_data.strResourceTypeName);

		// create Resource in Region1
		objResource
				.navigateToResourceListPage()
				.clickOnCreateNewResourceButton()
				.enterResourceName(objResource_data.strResourceName)
				.enterResourceAbbrivation(
						objResource_data.strResourceAbbrivation)
				.selectResourceTypename(
						objResourceType_data.strResourceTypeName)
				.selectStandardResourceTypename(
						objResource_data.strStandardResourceTypename)
				.enterResourceFirstName(objResource_data.strResourceFirstName)
				.enterResourceLastName(objResource_data.strResourceLastName)
				.enterStreetAddress(objResource_data.strStreetAddress)
				.selectState(objResource_data.strState)
				.enterCity(objResource_data.strCity)
				.enterzipCode(objResource_data.strZipcode)
				.selectCounty(objResource_data.strCounty)
				.clickOnLookupAddressBtn().verMap();

		String strLatitude = objResource.getLatitude();
		String strLogitude = objResource.getLongitude();

		strStdResourceValue[0] = objResource
				.getStandardResourceValue(objResource_data.strStandardResourceTypename);

		objResource.clickOnSaveButton().clickOnViewResChkBox()
				.clickOnSaveButton();

		objSelectRegion.selectRegionAndNavigate(objLogin_data.strRegionName4
				.trim());

		objRegionDefault.selectFrame();

		objNavigationToSubmenus.navigateToStatusTypesInSetup();

		// RoleBased Status Types in Region2
		objStatusTypeList
				.clickCreateNewStatusTypeButton()
				.selectStatusType(objStatuTypes_data.strNumberStatusType)
				.clickNextButton()
				.enterStatusTypeName(objStatuTypes_data.strNSTStatusTypeName1)
				.enterStatusTypeDescription(
						objStatuTypes_data.strStatusDescription)
				.selectStandardStatusTypename(
						objStatuTypes_data.strStandardStatusTypename);

		strStdStatusValueInReg2[0] = objStatusTypeList
				.getStandardStatusValue(objStatuTypes_data.strStandardStatusTypename);

		objStatusTypeList.clickOnSaveButton();

		strstatusTypeValuesInReg2[0] = objStatusTypeList
				.getStatusValue(objStatuTypes_data.strNSTStatusTypeName1);

		// Resource type creation in Region1
		objResourceType.navigateToResourceTypePage().createResourceType(
				objResourceType_data.strResourceTypeName1,
				strstatusTypeValuesInReg2);

		strResourceTypeValueInReg2[0] = objResourceType
				.getResourceTypeValue(objResourceType_data.strResourceTypeName1);

		// create Resource in Region2
		objResource
				.navigateToResourceListPage()
				.clickOnCreateNewResourceButton()
				.enterResourceName(objResource_data.strResourceName1)
				.enterResourceAbbrivation(
						objResource_data.strResourceAbbrivation)
				.selectResourceTypename(
						objResourceType_data.strResourceTypeName1)
				.selectStandardResourceTypename(
						objResource_data.strStandardResourceTypename)
				.enterResourceFirstName(objResource_data.strResourceFirstName)
				.enterResourceLastName(objResource_data.strResourceLastName)
				.enterStreetAddress(objResource_data.strStreetAddress)
				.selectState(objResource_data.strState)
				.enterCity(objResource_data.strCity)
				.enterzipCode(objResource_data.strZipcode)
				.selectCounty(objResource_data.strCounty)
				.clickOnLookupAddressBtn().verMap();

		String strLatitudeInReg2 = objResource.getLatitude();
		String strLogitudeInReg2 = objResource.getLongitude();

		strStdResourceValueInReg2[0] = objResource
				.getStandardResourceValue(objResource_data.strStandardResourceTypename);

		objResource.clickOnSaveButton().clickOnViewResChkBox()
				.clickOnSaveButton();

		objLogin.clickLogOut();

		System.out
				.println("-----Precondition ends and test execution starts-------");

		objLogin1.loginToApplication(objLogin_data.strUserName,
				objLogin_data.strPassword);

		objRegionDefault1.selectFrame();

		objSelectRegion1.selectRegionAndNavigate(objLogin_data.strRegionStatewideFlorida);

		objRegionDefault1.selectFrame();

		objNavigationToSubMenus1.clickOnResourceReports();

		objReport1.verifyResourceReportMenuPage()
				.clickOnStatewideResourceDetails()
				.verifyStatewideResourceDetailReportPage()
				.selectStandardResources(strStdResourceValue)
				.clickOnNextButtonInResourceDetailPage()
				.selectStandardStatus(strStdStatusValue)
				.clickOnGenerateReportBtn();

		Thread.sleep(20000);
		objAutoIT.DownloadTheReports(strAutoItPath, strDownloadName,
				strAutoITName);
		int intCount = 0;
		int intCount1 = 0;
		do {

			try {
				assertTrue(new File(strDownloadName).exists());
				Thread.sleep(10000);
				Runtime.getRuntime().exec(
						"wscript " + autoItFiles + filePath + " "
								+ strCSVFileNameRenamed);

				intCount1 = 0;
				do {
					try {
						assertTrue(new File(strCSVDownlRenamedPath).exists());
						break;
					} catch (AssertionError Ae) {
						Thread.sleep(1000);
						intCount1++;
					}

				} while (intCount1 < 60);

				break;
			} catch (AssertionError Ae) {
				Thread.sleep(1000);
				intCount++;
			}
		} while (intCount < 60);
		
		String strValue = objOffCommonFunc.readInfoExcel(
				"Statewide Resource Detail Repor", 1, 1, strDownloadName1);
		assertEquals(objReport_data.strStatewideResourceDetailReport, strValue);

		int intRowCount = objOffCommonFunc.getRowsCountOfExceSheet(
				strDownloadName1, "Statewide Resource Detail Repor");

		String[] strHeaderNames =objReport_data.StatewideReportHeaders;

		String[] strAnswers = {
				objLogin_data.strRegionStatewideFlorida,
				objResource_data.strResourceName,
				objResourceType_data.strResourceTypeName,
				objResource_data.strStreetAddress + ", "
						+ objResource_data.strCity + ", "
						+ objResource_data.strCaliforniaCode + " "
						+ objResource_data.strZipcode + "",
				objResource_data.strCounty, strLogitude, strLatitude, "", "",
				"", "", "FN LN", "", "", "", "", "", "0" };

		String[] strAnswers2 = {
				objLogin_data.strRegionName4,
				objResource_data.strResourceName1,
				objResourceType_data.strResourceTypeName1,
				objResource_data.strStreetAddress + ", "
						+ objResource_data.strCity + ", "
						+ objResource_data.strCaliforniaCode + " "
						+ objResource_data.strZipcode + "",
				objResource_data.strCounty, strLogitudeInReg2,
				strLatitudeInReg2, "", "", "", "", "FN LN", "", "", "", "", "",
				"0" };

		for (int i = 1; i <= strHeaderNames.length; i++) {
			strValue = objOffCommonFunc.readInfoExcel(
					"Statewide Resource Detail Repor", 2, i, strDownloadName1);
			assertEquals(strHeaderNames[i - 1], strValue);
		}
		System.out.println(objResource_data.strResourceName);
		System.out.println(objResource_data.strResourceName1);

		String strRes1 = objResource_data.strResourceName;
		String strRes2 = objResource_data.strResourceName1;
		System.out.println(strAnswers);
		System.out.println(strAnswers2);

		int intcnt = 0;
		for (int i = intRowCount; i <= intRowCount; i--) {
			if (i != 0) {
				strValue = objOffCommonFunc.readInfoExcel(
						"Statewide Resource Detail Repor", i, 2,
						strDownloadName1);
				if (strValue.contains(strRes1) || strValue.contains(strRes2)) {
					for (int j = 1; j <= strAnswers.length; j++) {
						strValue = objOffCommonFunc.readInfoExcel(
								"Statewide Resource Detail Repor", i, j,
								strDownloadName1);
						assertTrue(strValue.contains(strAnswers[j - 1])
								|| strValue.contains(strAnswers2[j - 1]));
					}
					intcnt++;
				}
			}
			if (intcnt == 2)
				break;
		}
	
		gstrResult = "PASS";
	}	
	
	/******************************************************************************************
	'Description : Verify that for a text status types created with same standard statuses the 
	               updates are displayed appropriately in the report generated.
	'Date	 	 : 8-Feb-2014
	'Author		 : Anitha
	'------------------------------------------------------------------------------------------
	'Modified Date			                        	Modified By
	'Date					                            Name
	********************************************************************************************/
	@Test(description = "Verify that for a text status types created with same standard statuses the "
			+ "updates are displayed appropriately in the report generated.")
	public void testHappyDay99555() throws Exception {

		gstrTCID = "99555";
		gstrTO = "Verify that for a text status types created with same standard statuses the updates are"
				+ " displayed appropriately in the report generated.";

		Login_data objLogin_data = new Login_data();
		ResourceType_data objResourceType_data = new ResourceType_data();
		Resource_data objResource_data = new Resource_data();
		StatusTypes_data objStatuTypes_data = new StatusTypes_data();
		Report_data objReport_data = new Report_data();
		User_data objUserdata = new User_data();
		View_data objView_data = new View_data();
		PathsProperties objAP = new PathsProperties();
		Roles_data objRolesData = new Roles_data();
		Properties pathProps = objAP.ReadAutoit_FilePath();
		Date_Time_settings dts = new Date_Time_settings();
		OfficeCommonFunctions objOffCommonFunc = new OfficeCommonFunctions();

		String strTimeText = dts.getCurrentDate(objReport_data.dateFormat1);
		String fileType = objReport_data.reportFile;
		Login objLogin = new Login(this.driver1);
		UsersList objUsersList = new UsersList(this.driver1);
		Roles objRoles = new Roles(this.driver1);
		SelectRegion objSelectRegion = new SelectRegion(this.driver1);
		RegionDefault objRegionDefault = new RegionDefault(this.driver1);
		StatusTypeList objStatusTypeList = new StatusTypeList(this.driver1);
		ResourceType objResourceType = new ResourceType(this.driver1);
		Resource objResource = new Resource(this.driver1);
		Regions objRegions_page = new Regions(this.driver1);
		NavigationToSubMenus objNavigationToSubmenus = new NavigationToSubMenus(
				this.driver1);

		AutoIT objAutoIT = new AutoIT(this.driver1);
		Report objReport1 = new Report(this.driver1);
		Map objMap = new Map(this.driver1);
		Login objLogin1 = new Login(this.driver1);
		SelectRegion objSelectRegion1 = new SelectRegion(this.driver1);
		RegionDefault objRegionDefault1 = new RegionDefault(this.driver1);
		UpdateStatus objUpdateStatus = new UpdateStatus(this.driver1);
		NavigationToSubMenus objNavigationToSubMenus1 = new NavigationToSubMenus(
				this.driver1);

		String strstatusTypeValues[] = new String[1];
		String strstatusTypeValues1[] = new String[1];
		String strStdStatusValue[] = new String[1];
		String strStdResourceValue[] = new String[1];
		String strResourceTypeValue[] = new String[1];
		String strRoleValue[] = new String[1];
		String strRegionValue[] = new String[2];

		String strstatusTypeValuesInReg2[] = new String[1];
		String strStdStatusValueInReg2[] = new String[1];
		String strResourceTypeValueInReg2[] = new String[1];
		String strStdResourceValueInReg2[] = new String[1];

		String AutoIT_FILE_PATH = objReport_data.reportsDownloadAutoItPath;
		String strAutoItPath = ReadAutoItProperty
				.readDataFromAutoItPath(AutoIT_FILE_PATH);
		String strAutoITName = pathProps
				.getProperty(objReport_data.reportsDownloadAutoItName);
		String fileDownloadPath = pathProps
				.getProperty(objReport_data.reportsDownloadPath);

		String autoItFilesPath = pathProps
				.getProperty(objReport_data.autoItPath);

		File file = new File(System.getProperty("user.dir") + fileDownloadPath);

		File autoItFiles = new File(System.getProperty("user.dir")
				+ autoItFilesPath);

		String strDownloadName = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + fileType;
		String strCSVFileNameRenamed = "TC" + gstrTCID + "_" + strTimeText;

		String strCSVDownlRenamedPath = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + objReport_data.xlsFile;

		String strDownloadName1 = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + objReport_data.xlsFile;

		String filePath = file + "\\";

		objLogin.loginToApplication(objLogin_data.strUserName,
				objLogin_data.strPassword);

		objSelectRegion.selectRegionAndNavigate(objLogin_data.strRegionStatewideFlorida);

		objRegionDefault.selectFrame();

		objNavigationToSubmenus.navigateToRegions();

		strRegionValue[0] = objRegions_page
				.getRegionValue(objLogin_data.strRegionStatewideFlorida);

		strRegionValue[1] = objRegions_page
				.getRegionValue(objLogin_data.strRegionName4);

		objNavigationToSubmenus.navigateToStatusTypesInSetup();

		// RoleBased Status Types in Region1// TST1
		objStatusTypeList
				.clickCreateNewStatusTypeButton()
				.selectStatusType(objStatuTypes_data.strTextStatusType)
				.clickNextButton()
				.enterStatusTypeName(objStatuTypes_data.strTSTStatusTypeName)
				.enterStatusTypeDescription(
						objStatuTypes_data.strStatusDescription)
				.selectStandardStatusTypename(
						objStatuTypes_data.strStandardStatusTypename3);

		strStdStatusValue[0] = objStatusTypeList
				.getStandardStatusValue(objStatuTypes_data.strStandardStatusTypename3);

		System.out.println(strStdStatusValue[0]);

		objStatusTypeList.clickOnSaveButton();

		strstatusTypeValues[0] = objStatusTypeList
				.getStatusValue(objStatuTypes_data.strTSTStatusTypeName);
		
		// TST2
		objStatusTypeList
				.clickCreateNewStatusTypeButton()
				.selectStatusType(objStatuTypes_data.strTextStatusType)
				.clickNextButton()
				.enterStatusTypeName(objStatuTypes_data.strTSTStatusTypeName1)
				.enterStatusTypeDescription(
						objStatuTypes_data.strStatusDescription)
				.selectStandardStatusTypename(
						objStatuTypes_data.strStandardStatusTypename3);

		strStdStatusValue[0] = objStatusTypeList
				.getStandardStatusValue(objStatuTypes_data.strStandardStatusTypename3);

		System.out.println(strStdStatusValue[0]);

		objStatusTypeList.clickOnSaveButton();

		strstatusTypeValues1[0] = objStatusTypeList
				.getStatusValue(objStatuTypes_data.strTSTStatusTypeName1);

		// Resource type creation in Region1
		objResourceType.navigateToResourceTypePage().createResourceType(
				objResourceType_data.strResourceTypeName, strstatusTypeValues);

		strResourceTypeValue[0] = objResourceType
				.getResourceTypeValue(objResourceType_data.strResourceTypeName);

		// create Resource in Region1
		objResource
				.navigateToResourceListPage()
				.clickOnCreateNewResourceButton()
				.enterResourceName(objResource_data.strResourceName)
				.enterResourceAbbrivation(
						objResource_data.strResourceAbbrivation)
				.selectResourceTypename(
						objResourceType_data.strResourceTypeName)
				.selectStandardResourceTypename(
						objResource_data.strStandardResourceTypename2)
				.enterResourceFirstName(objResource_data.strResourceFirstName)
				.enterResourceLastName(objResource_data.strResourceLastName)
				.enterStreetAddress(objResource_data.strStreetAddress)
				.selectState(objResource_data.strState)
				.enterCity(objResource_data.strCity)
				.enterzipCode(objResource_data.strZipcode)
				.selectCounty(objResource_data.strCounty)
				.clickOnLookupAddressBtn().verMap();

		String strLatitude = objResource.getLatitude();
		String strLogitude = objResource.getLongitude();

		strStdResourceValue[0] = objResource
				.getStandardResourceValue(objResource_data.strStandardResourceTypename2);
		
		objResource.clickOnSaveButton().clickOnViewResChkBox()
				.clickOnSaveButton();
		
		objResource.clickOnStatusTypeLinkInResourcePage(objResource_data.strResourceName)
		.selectStatusType(strstatusTypeValues1).clickOnSaveButton();
		
		// Create role
		objNavigationToSubmenus.navigateToRoles();

		objRoles.clickOnCreateNewRoleBtn()
				.enterRoleName(objRolesData.strRoleName1)
				.clickStatusTypeInRoleMayViewSection(strstatusTypeValues)
				.clickStatusTypeInRoleMayUpdateSection(strstatusTypeValues)
				.clickStatusTypeInRoleMayViewSection(strstatusTypeValues1)
				.clickStatusTypeInRoleMayUpdateSection(strstatusTypeValues1);
		objUsersList.selectReportStatewideResourceDetail();
		objRoles.clickOnSaveBtn();

		strRoleValue[0] = objRoles.getRoleValue(objRolesData.strRoleName1);
		
		// User creation
		objUsersList
				.navigateToUsersNew()
				.clickCreateNewUserButton()
				.enterUserDetails(objUserdata.strNewUserName,
						objUserdata.strNewPassword, objUserdata.strFullName)
				.selectRoleCheckBox(strRoleValue[0])
				.selectViewResourceRights(objResource_data.strResourceName)
				.selectUpdateStatusOfResource(objResource_data.strResourceName)
				.clickSaveButton()
				.searchUserName(objUserdata.strNewUserName,
						objUserdata.strRole, objUserdata.strResourceType,
						objUserdata.strUsername, objUserdata.strsearchOption)
				.clickRegionsLinkForUser(objUserdata.strNewUserName)
				.selectRegion(strRegionValue[1]).clickSaveButton();
		
		System.out.println(objUserdata.strNewUserName);

		//Another region
		objSelectRegion.selectRegionAndNavigate(objLogin_data.strRegionName4
				.trim());

		objRegionDefault.selectFrame();

		objNavigationToSubmenus.navigateToStatusTypesInSetup();

		// RoleBased Status Types in Region2
		objStatusTypeList
				.clickCreateNewStatusTypeButton()
				.selectStatusType(objStatuTypes_data.strTextStatusType)
				.clickNextButton()
				.enterStatusTypeName(objStatuTypes_data.strTSTStatusTypeName2)
				.enterStatusTypeDescription(
						objStatuTypes_data.strStatusDescription)
				.selectStandardStatusTypename(
						objStatuTypes_data.strStandardStatusTypename3);

		strStdStatusValueInReg2[0] = objStatusTypeList
				.getStandardStatusValue(objStatuTypes_data.strStandardStatusTypename3);

		objStatusTypeList.clickOnSaveButton();

		strstatusTypeValuesInReg2[0] = objStatusTypeList
				.getStatusValue(objStatuTypes_data.strTSTStatusTypeName2);

		// Resource type creation in Region1
		objResourceType.navigateToResourceTypePage().createResourceType(
				objResourceType_data.strResourceTypeName1,
				strstatusTypeValuesInReg2);

		strResourceTypeValueInReg2[0] = objResourceType
				.getResourceTypeValue(objResourceType_data.strResourceTypeName1);

		// create Resource in Region2
		objResource
				.navigateToResourceListPage()
				.clickOnCreateNewResourceButton()
				.enterResourceName(objResource_data.strResourceName1)
				.enterResourceAbbrivation(
						objResource_data.strResourceAbbrivation)
				.selectResourceTypename(
						objResourceType_data.strResourceTypeName1)
				.selectStandardResourceTypename(
						objResource_data.strStandardResourceTypename2)
				.enterResourceFirstName(objResource_data.strResourceFirstName)
				.enterResourceLastName(objResource_data.strResourceLastName)
				.enterStreetAddress(objResource_data.strStreetAddress)
				.selectState(objResource_data.strState)
				.enterCity(objResource_data.strCity)
				.enterzipCode(objResource_data.strZipcode)
				.selectCounty(objResource_data.strCounty)
				.clickOnLookupAddressBtn().verMap();

		String strLatitudeInReg2 = objResource.getLatitude();
		String strLogitudeInReg2 = objResource.getLongitude();

		strStdResourceValueInReg2[0] = objResource
				.getStandardResourceValue(objResource_data.strStandardResourceTypename2);

		objResource.clickOnSaveButton().clickOnViewResChkBox()
				.clickOnSaveButton();

		objLogin.clickLogOut();

		System.out.println("-----Precondition ends and test execution starts-------");

		objLogin1.loginAsNewUser(objUserdata.strNewUserName,
				objUserdata.strNewPassword);

		objSelectRegion1.selectRegionAndNavigate(objLogin_data.strRegionStatewideFlorida);

		objRegionDefault1.selectFrame();

		objNavigationToSubMenus1.navigateToMap();

		objMap.selectResourceNameInFindResourceDropdown(
				objResource_data.strResourceName)
				.verUpdateStatusInPopupWindow()
				.clickUpdateStatusInPopupWindow();

		objUpdateStatus
				.selectStatusTypes(strstatusTypeValues[0])
				.enterNSTAndTSTUpdateValue(strstatusTypeValues[0],
						objView_data.strValueForUpdate)
				.selectStatusTypes(strstatusTypeValues1[0])
				.enterNSTAndTSTUpdateValue(strstatusTypeValues1[0],
						objView_data.strValueForUpdate1).clickOnSaveButton();
		
		//Generate Report
		objNavigationToSubMenus1.clickOnResourceReports();

		objReport1.verifyResourceReportMenuPage()
				.clickOnStatewideResourceDetails()
				.verifyStatewideResourceDetailReportPage()
				.selectStandardResources(strStdResourceValue)
				.clickOnNextButtonInResourceDetailPage()
				.selectStandardStatus(strStdStatusValue)
				.clickOnGenerateReportBtn();

		Thread.sleep(20000);
		objAutoIT.DownloadTheReports(strAutoItPath, strDownloadName,
				strAutoITName);
		int intCount = 0;
		int intCount1 = 0;
		do {

			try {
				assertTrue(new File(strDownloadName).exists());
				Thread.sleep(10000);
				Runtime.getRuntime().exec(
						"wscript " + autoItFiles + filePath + " "
								+ strCSVFileNameRenamed);

				intCount1 = 0;
				do {
					try {
						assertTrue(new File(strCSVDownlRenamedPath).exists());
						break;
					} catch (AssertionError Ae) {
						Thread.sleep(1000);
						intCount1++;
					}

				} while (intCount1 < 60);

				break;
			} catch (AssertionError Ae) {
				Thread.sleep(1000);
				intCount++;
			}
		} while (intCount < 60);
		
		String strValue = objOffCommonFunc.readInfoExcel(
				"Statewide Resource Detail Repor", 1, 1, strDownloadName1);
		assertEquals(objReport_data.strStatewideResourceDetailReport, strValue);

		int intRowCount = objOffCommonFunc.getRowsCountOfExceSheet(
				strDownloadName1, "Statewide Resource Detail Repor");

		String[] strHeaderNames = { "Region", "Resource Name", "Type",
				"Address", "County", "Latitude", "Longitude", "EMResource ID",
				"AHA ID", "External ID", "Website", "Contact", "Phone 1",
				"Phone 2", "Fax", "Email", "Notes", "CEO Name" };

		String[] strAnswers = {
				objLogin_data.strRegionStatewideFlorida,
				objResource_data.strResourceName,
				objResourceType_data.strResourceTypeName,
				objResource_data.strStreetAddress + ", "
						+ objResource_data.strCity + ", "
						+ objResource_data.strCaliforniaCode + " "
						+ objResource_data.strZipcode + "",
				objResource_data.strCounty, strLogitude, strLatitude, "", "",
				"", "", "FN LN", "", "", "", "", "", "2; 1" };

		String[] strAnswers2 = {
				objLogin_data.strRegionName4,
				objResource_data.strResourceName1,
				objResourceType_data.strResourceTypeName1,
				objResource_data.strStreetAddress + ", "
						+ objResource_data.strCity + ", "
						+ objResource_data.strCaliforniaCode + " "
						+ objResource_data.strZipcode + "",
				objResource_data.strCounty, strLogitudeInReg2,
				strLatitudeInReg2, "", "", "", "", "FN LN", "", "", "", "", "",
				"" };

		for (int i = 1; i <= strHeaderNames.length; i++) {
			strValue = objOffCommonFunc.readInfoExcel(
					"Statewide Resource Detail Repor", 2, i, strDownloadName1);
			assertEquals(strHeaderNames[i - 1], strValue);
		}
		System.out.println(objResource_data.strResourceName);
		System.out.println(objResource_data.strResourceName1);

		String strRes1 = objResource_data.strResourceName;
		String strRes2 = objResource_data.strResourceName1;
		System.out.println(strAnswers);
		System.out.println(strAnswers2);

		int intcnt = 0;
		for (int i = intRowCount; i <= intRowCount; i--) {
			if (i != 0) {
				strValue = objOffCommonFunc.readInfoExcel(
						"Statewide Resource Detail Repor", i, 2,
						strDownloadName1);
				if (strValue.contains(strRes1) || strValue.contains(strRes2)) {
					for (int j = 1; j <= strAnswers.length; j++) {
						strValue = objOffCommonFunc.readInfoExcel(
								"Statewide Resource Detail Repor", i, j,
								strDownloadName1);
						assertTrue(strValue.contains(strAnswers[j - 1])
								|| strValue.contains(strAnswers2[j - 1]));
					}
					intcnt++;
				}
			}
			if (intcnt == 2)
				break;
		}

		gstrResult = "PASS";
	}

	/************************************************************************************************************
	'Description : Verify that the resource information edited is displayed appropriately in the generated report 
	'Date	 	 : 04-Feb-2016
	'Author		 : Anil
	'-----------------------------------------------------------------------------------------------------------
	'Modified Date			                        	Modified By
	'Date					                            Name
	************************************************************************************************************/
	@Test(description = "Verify that the resource information edited is displayed appropriately in the generated report ")
	public void testHappyDay99092() throws Exception {

		gstrTCID = "99092";
		gstrTO = "Verify that the resource information edited is displayed appropriately in the generated report ";

		Login_data objLogin_data = new Login_data();
		ResourceType_data objResourceType_data = new ResourceType_data();
		Resource_data objResource_data = new Resource_data();
		StatusTypes_data objStatuTypes_data = new StatusTypes_data();
		Report_data objReport_data = new Report_data();
		PathsProperties objAP = new PathsProperties();
		Properties pathProps = objAP.ReadAutoit_FilePath();
		Date_Time_settings dts = new Date_Time_settings();
		OfficeCommonFunctions objOffCommonFunc = new OfficeCommonFunctions();

		String strTimeText = dts.getCurrentDate(objReport_data.dateFormat1);
		String fileType = objReport_data.reportFile;
		Login objLogin = new Login(this.driver1);
		SelectRegion objSelectRegion = new SelectRegion(this.driver1);
		RegionDefault objRegionDefault = new RegionDefault(this.driver1);
		StatusTypeList objStatusTypeList = new StatusTypeList(this.driver1);
		ResourceType objResourceType = new ResourceType(this.driver1);
		Resource objResource = new Resource(this.driver1);
		NavigationToSubMenus objNavigationToSubmenus = new NavigationToSubMenus(
				this.driver1);

		AutoIT objAutoIT = new AutoIT(this.driver1);
		Report objReport1 = new Report(this.driver1);
		NavigationToSubMenus objNavigationToSubMenus1 = new NavigationToSubMenus(
				this.driver1);
		Login objLogin1 = new Login(this.driver1);
		SelectRegion objSelectRegion1 = new SelectRegion(this.driver1);
		RegionDefault objRegionDefault1 = new RegionDefault(this.driver1);
		Resource objResource1 = new Resource(this.driver1);
		
		String strstatusTypeValues[] = new String[1];
		String strStdStatusValue[] = new String[1];
		String strStdResourceValue[] = new String[1];
		String strResourceTypeValue[] = new String[1];

		String strstatusTypeValuesInReg2[] = new String[1];
		String strStdStatusValueInReg2[] = new String[1];
		String strResourceTypeValueInReg2[] = new String[1];
		String strStdResourceValueInReg2[] = new String[1];

		String AutoIT_FILE_PATH = objReport_data.reportsDownloadAutoItPath;
		String strAutoItPath = ReadAutoItProperty
				.readDataFromAutoItPath(AutoIT_FILE_PATH);
		String strAutoITName = pathProps
				.getProperty(objReport_data.reportsDownloadAutoItName);
		String fileDownloadPath = pathProps
				.getProperty(objReport_data.reportsDownloadPath);

		String autoItFilesPath = pathProps
				.getProperty(objReport_data.autoItPath);

		File file = new File(System.getProperty("user.dir") + fileDownloadPath);

		File autoItFiles = new File(System.getProperty("user.dir")
				+ autoItFilesPath);

		String strDownloadName = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + fileType;
		String strCSVFileNameRenamed = "TC" + gstrTCID + "_" + strTimeText;

		String strCSVDownlRenamedPath = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + objReport_data.xlsFile;

		String strDownloadName1 = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + objReport_data.xlsFile;

		String filePath = file + "\\";
String strLogitude = "";
String strLatitudeInReg2 = "";
String strLogitudeInReg2 ="";
String strLatitude = "";

		objLogin.loginToApplication(objLogin_data.strUserName,
				objLogin_data.strPassword);

		objSelectRegion.selectRegionAndNavigate(objLogin_data.strRegionStatewideFlorida);

		objRegionDefault.selectFrame();

		objNavigationToSubmenus.navigateToStatusTypesInSetup();

		// RoleBased Status Types in Region1
		objStatusTypeList
				.clickCreateNewStatusTypeButton()
				.selectStatusType(objStatuTypes_data.strNumberStatusType)
				.clickNextButton()
				.enterStatusTypeName(objStatuTypes_data.strNSTStatusTypeName)
				.enterStatusTypeDescription(
						objStatuTypes_data.strStatusDescription)
				.selectStandardStatusTypename(
						objStatuTypes_data.strStandardStatusTypename);

		strStdStatusValue[0] = objStatusTypeList
				.getStandardStatusValue(objStatuTypes_data.strStandardStatusTypename);

		System.out.println(strStdStatusValue[0]);

		objStatusTypeList.clickOnSaveButton();

		strstatusTypeValues[0] = objStatusTypeList
				.getStatusValue(objStatuTypes_data.strNSTStatusTypeName);


		// Resource type creation in Region1
		objResourceType.navigateToResourceTypePage().createResourceType(
				objResourceType_data.strResourceTypeName, strstatusTypeValues);

		strResourceTypeValue[0] = objResourceType
				.getResourceTypeValue(objResourceType_data.strResourceTypeName);

		// create Resource in Region1
		objResource
				.navigateToResourceListPage()
				.clickOnCreateNewResourceButton()
				.enterResourceName(objResource_data.strResourceName)
				.enterResourceAbbrivation(
						objResource_data.strResourceAbbrivation)
				.selectResourceTypename(
						objResourceType_data.strResourceTypeName)
				.selectStandardResourceTypename(
						objResource_data.strStandardResourceTypename)
				.enterResourceFirstName(objResource_data.strResourceFirstName)
				.enterResourceLastName(objResource_data.strResourceLastName)
				.enterStreetAddress(objResource_data.strStreetAddress)
				.selectState(objResource_data.strState)
				.enterCity(objResource_data.strCity)
				.enterzipCode(objResource_data.strZipcode)
				.selectCounty(objResource_data.strCounty)
				.clickOnLookupAddressBtn().verMap();

		 strLatitude = objResource.getLatitude();
		strLogitude = objResource.getLongitude();

		strStdResourceValue[0] = objResource
				.getStandardResourceValue(objResource_data.strStandardResourceTypename);

		objResource.clickOnSaveButton().clickOnViewResChkBox()
				.clickOnSaveButton();

		objSelectRegion.selectRegionAndNavigate(objLogin_data.strRegionName4
				.trim());

		objRegionDefault.selectFrame();

		objNavigationToSubmenus.navigateToStatusTypesInSetup();

		// RoleBased Status Types in Region2
		objStatusTypeList
				.clickCreateNewStatusTypeButton()
				.selectStatusType(objStatuTypes_data.strNumberStatusType)
				.clickNextButton()
				.enterStatusTypeName(objStatuTypes_data.strNSTStatusTypeName1)
				.enterStatusTypeDescription(
						objStatuTypes_data.strStatusDescription)
				.selectStandardStatusTypename(
						objStatuTypes_data.strStandardStatusTypename);

		strStdStatusValueInReg2[0] = objStatusTypeList
				.getStandardStatusValue(objStatuTypes_data.strStandardStatusTypename);

		objStatusTypeList.clickOnSaveButton();

		strstatusTypeValuesInReg2[0] = objStatusTypeList
				.getStatusValue(objStatuTypes_data.strNSTStatusTypeName1);

		// Resource type creation in Region1
		objResourceType.navigateToResourceTypePage().createResourceType(
				objResourceType_data.strResourceTypeName1,
				strstatusTypeValuesInReg2);

		strResourceTypeValueInReg2[0] = objResourceType
				.getResourceTypeValue(objResourceType_data.strResourceTypeName1);

		// create Resource in Region2
		objResource
				.navigateToResourceListPage()
				.clickOnCreateNewResourceButton()
				.enterResourceName(objResource_data.strResourceName1)
				.enterResourceAbbrivation(
						objResource_data.strResourceAbbrivation)
				.selectResourceTypename(
						objResourceType_data.strResourceTypeName1)
				.selectStandardResourceTypename(
						objResource_data.strStandardResourceTypename)
				.enterResourceFirstName(objResource_data.strResourceFirstName)
				.enterResourceLastName(objResource_data.strResourceLastName)
				.enterStreetAddress(objResource_data.strStreetAddress)
				.selectState(objResource_data.strState)
				.enterCity(objResource_data.strCity)
				.enterzipCode(objResource_data.strZipcode)
				.selectCounty(objResource_data.strCounty)
				.clickOnLookupAddressBtn().verMap();

		strLatitudeInReg2 = objResource.getLatitude();
		strLogitudeInReg2 = objResource.getLongitude();

		strStdResourceValueInReg2[0] = objResource
				.getStandardResourceValue(objResource_data.strStandardResourceTypename);

		objResource.clickOnSaveButton().clickOnViewResChkBox()
				.clickOnSaveButton();

		objLogin.clickLogOut();

		System.out
				.println("-----Precondition ends and test execution starts-------");

		objLogin1.loginToApplication(objLogin_data.strUserName,
				objLogin_data.strPassword);

		objSelectRegion1.selectRegionAndNavigate(objLogin_data.strRegionName4.trim());

		objRegionDefault1.selectFrame();

		objResource1
		.navigateToResourceListPageNew()
		.clickOnEditLinkInResourcePage(objResource_data.strResourceName1)
		.enterResourceName(objResource_data.strEditedResName1)
		.enterResourceAbbrivation(
				objResource_data.strEditedResAbb2)
		.selectStandardResourceTypename(
				objResource_data.strStandardResourceTypename1)
		.enterResourceFirstName(objResource_data.strEditedResourceFirstName)
		.enterResourceLastName(objResource_data.strEditedResourceLastName)
		.enterStreetAddress(objResource_data.strEditedStreetAddress)
		.selectState(objResource_data.strEditedState)
		.enterCity(objResource_data.strEditedCity)
		.enterzipCode(objResource_data.strEditedZipcode)
		.selectCounty(objResource_data.strEditedCounty)
		.clickOnLookupAddressBtn().verMap();
		
		strStdResourceValue[0] = objResource1
				.getStandardResourceValue(objResource_data.strStandardResourceTypename1);
		
		strLatitudeInReg2 = objResource1.getLatitude();
		strLogitudeInReg2 = objResource1.getLongitude();
		
		objResource1.clickOnSaveButton();

		
		objSelectRegion1.selectRegionAndNavigate(objLogin_data.strRegionStatewideFlorida);

		objRegionDefault1.selectFrame();

		objResource1
		.navigateToResourceListPageNew()
		.clickOnEditLinkInResourcePage(objResource_data.strResourceName)
		.enterResourceName(objResource_data.strEditedResName)
		.enterResourceAbbrivation(
				objResource_data.strEditedResAbb2)
		.selectStandardResourceTypename(
				objResource_data.strStandardResourceTypename1)
		.enterResourceFirstName(objResource_data.strEditedResourceFirstName)
		.enterResourceLastName(objResource_data.strEditedResourceLastName)
		.enterStreetAddress(objResource_data.strEditedStreetAddress)
		.selectState(objResource_data.strEditedState)
		.enterCity(objResource_data.strEditedCity)
		.enterzipCode(objResource_data.strEditedZipcode)
		.selectCounty(objResource_data.strEditedCounty)
		.clickOnLookupAddressBtn().verMap();
		
		strStdResourceValue[0] = objResource1
				.getStandardResourceValue(objResource_data.strStandardResourceTypename1);
		
		strLatitude = objResource1.getLatitude();
		strLogitude = objResource1.getLongitude();
		
		objResource1.clickOnSaveButton();
		
		objNavigationToSubMenus1.clickOnResourceReports();

		objReport1.verifyResourceReportMenuPage()
				.clickOnStatewideResourceDetails()
				.verifyStatewideResourceDetailReportPage()
				.selectStandardResources(strStdResourceValue)
				.clickOnNextButtonInResourceDetailPage()
				.selectStandardStatus(strStdStatusValue)
				.clickOnGenerateReportBtn();

		Thread.sleep(20000);
		objAutoIT.DownloadTheReports(strAutoItPath, strDownloadName,
				strAutoITName);
		int intCount = 0;
		int intCount1 = 0;
		do {

			try {
				assertTrue(new File(strDownloadName).exists());
				Thread.sleep(10000);
				Runtime.getRuntime().exec(
						"wscript " + autoItFiles + filePath + " "
								+ strCSVFileNameRenamed);

				intCount1 = 0;
				do {
					try {
						assertTrue(new File(strCSVDownlRenamedPath).exists());
						break;
					} catch (AssertionError Ae) {
						Thread.sleep(1000);
						intCount1++;
					}

				} while (intCount1 < 60);

				break;
			} catch (AssertionError Ae) {
				Thread.sleep(1000);
				intCount++;
			}
		} while (intCount < 60);
		
		String strValue = objOffCommonFunc.readInfoExcel(
				"Statewide Resource Detail Repor", 1, 1, strDownloadName1);
		assertEquals(objReport_data.strStatewideResourceDetailReport, strValue);

		int intRowCount = objOffCommonFunc.getRowsCountOfExceSheet(
				strDownloadName1, "Statewide Resource Detail Repor");

		String[] strHeaderNames =objReport_data.StatewideReportHeaders;

		String[] strAnswers = {
				objLogin_data.strRegionStatewideFlorida,
				objResource_data.strEditedResName,
				objResourceType_data.strResourceTypeName,
				objResource_data.strEditedStreetAddress + ", "
						+ objResource_data.strEditedCity + ", "
						+ objResource_data.strLouisianaCode + " "
						+ objResource_data.strEditedZipcode + "",
				objResource_data.strEditedCounty, strLogitude, strLatitude, "", "",
				"", "", objResource_data.strEditedResourceFirstName+" "+objResource_data.strEditedResourceLastName, "", "", "", "", "", "0" };

		String[] strAnswers2 = {
				objLogin_data.strRegionName4,
				objResource_data.strEditedResName1,
				objResourceType_data.strResourceTypeName1,
				objResource_data.strEditedStreetAddress + ", "
						+ objResource_data.strEditedCity + ", "
						+ objResource_data.strLouisianaCode + " "
						+ objResource_data.strEditedZipcode + "",
				objResource_data.strEditedCounty, strLogitudeInReg2,
				strLatitudeInReg2, "", "", "", "",  objResource_data.strEditedResourceFirstName+" "+objResource_data.strEditedResourceLastName, "", "", "", "", "",
				"0" };

		for (int i = 1; i <= strHeaderNames.length; i++) {
			strValue = objOffCommonFunc.readInfoExcel(
					"Statewide Resource Detail Repor", 2, i, strDownloadName1);
			assertEquals(strHeaderNames[i - 1], strValue);
		}

		String strRes1 = objResource_data.strEditedResName;
		String strRes2 = objResource_data.strEditedResName1;
		System.out.println(strAnswers);
		System.out.println(strAnswers2);

		int intcnt = 0;
		for (int i = intRowCount; i <= intRowCount; i--) {
			if (i != 0) {
				strValue = objOffCommonFunc.readInfoExcel(
						"Statewide Resource Detail Repor", i, 2,
						strDownloadName1);
				if (strValue.contains(strRes1) || strValue.contains(strRes2)) {
					for (int j = 1; j <= strAnswers.length; j++) {
						strValue = objOffCommonFunc.readInfoExcel(
								"Statewide Resource Detail Repor", i, j,
								strDownloadName1);
						assertTrue(strValue.contains(strAnswers[j - 1])
								|| strValue.contains(strAnswers2[j - 1]));
					}
					intcnt++;
				}
			}
			if (intcnt == 2)
				break;
		}
	
		gstrResult = "PASS";
	}	
	
	/******************************************************************************************
	'Description : Verify that for a number status type created with same standard statuses gets
	               added up in the report generated. 
	'Date	 	 : 8-Feb-2014
	'Author		 : Anil
	'------------------------------------------------------------------------------------------
	'Modified Date			                        	Modified By
	'Date					                            Name
	********************************************************************************************/
	@Test(description = " 	Verify that for a number status type created with same standard statuses "
			+ "gets added up in the report generated. ")
	public void testHappyDay100381() throws Exception {

		gstrTCID = "100381";
		gstrTO = " 	Verify that for a number status type created with same standard statuses gets"
				+ " added up in the report generated. ";

		Login_data objLogin_data = new Login_data();
		ResourceType_data objResourceType_data = new ResourceType_data();
		Resource_data objResource_data = new Resource_data();
		StatusTypes_data objStatuTypes_data = new StatusTypes_data();
		Report_data objReport_data = new Report_data();
		User_data objUserdata = new User_data();
		View_data objView_data = new View_data();
		PathsProperties objAP = new PathsProperties();
		Roles_data objRolesData = new Roles_data();
		Properties pathProps = objAP.ReadAutoit_FilePath();
		Date_Time_settings dts = new Date_Time_settings();
		OfficeCommonFunctions objOffCommonFunc = new OfficeCommonFunctions();

		String strTimeText = dts.getCurrentDate(objReport_data.dateFormat1);
		String fileType = objReport_data.reportFile;
		Login objLogin = new Login(this.driver1);
		UsersList objUsersList = new UsersList(this.driver1);
		Roles objRoles = new Roles(this.driver1);
		SelectRegion objSelectRegion = new SelectRegion(this.driver1);
		RegionDefault objRegionDefault = new RegionDefault(this.driver1);
		StatusTypeList objStatusTypeList = new StatusTypeList(this.driver1);
		ResourceType objResourceType = new ResourceType(this.driver1);
		Resource objResource = new Resource(this.driver1);
		Regions objRegions_page = new Regions(this.driver1);
		NavigationToSubMenus objNavigationToSubmenus = new NavigationToSubMenus(
				this.driver1);

		AutoIT objAutoIT = new AutoIT(this.driver1);
		Report objReport1 = new Report(this.driver1);
		Map objMap = new Map(this.driver1);
		Login objLogin1 = new Login(this.driver1);
		SelectRegion objSelectRegion1 = new SelectRegion(this.driver1);
		RegionDefault objRegionDefault1 = new RegionDefault(this.driver1);
		UpdateStatus objUpdateStatus = new UpdateStatus(this.driver1);
		NavigationToSubMenus objNavigationToSubMenus1 = new NavigationToSubMenus(
				this.driver1);

		String strstatusTypeValues[] = new String[1];
		String strstatusTypeValues1[] = new String[1];
		String strStdStatusValue[] = new String[1];
		String strStdResourceValue[] = new String[1];
		String strResourceTypeValue[] = new String[1];
		String strRoleValue[] = new String[1];
		String strRegionValue[] = new String[2];

		String strstatusTypeValuesInReg2[] = new String[1];
		String strStdStatusValueInReg2[] = new String[1];
		String strResourceTypeValueInReg2[] = new String[1];
		String strStdResourceValueInReg2[] = new String[1];

		String AutoIT_FILE_PATH = objReport_data.reportsDownloadAutoItPath;
		String strAutoItPath = ReadAutoItProperty
				.readDataFromAutoItPath(AutoIT_FILE_PATH);
		String strAutoITName = pathProps
				.getProperty(objReport_data.reportsDownloadAutoItName);
		String fileDownloadPath = pathProps
				.getProperty(objReport_data.reportsDownloadPath);

		String autoItFilesPath = pathProps
				.getProperty(objReport_data.autoItPath);

		File file = new File(System.getProperty("user.dir") + fileDownloadPath);

		File autoItFiles = new File(System.getProperty("user.dir")
				+ autoItFilesPath);

		String strDownloadName = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + fileType;
		String strCSVFileNameRenamed = "TC" + gstrTCID + "_" + strTimeText;

		String strCSVDownlRenamedPath = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + objReport_data.xlsFile;

		String strDownloadName1 = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + objReport_data.xlsFile;

		String filePath = file + "\\";

		objLogin.loginToApplication(objLogin_data.strUserName,
				objLogin_data.strPassword);

		objSelectRegion.selectRegionAndNavigate(objLogin_data.strRegionStatewideFlorida);

		objRegionDefault.selectFrame();

		objNavigationToSubmenus.navigateToRegions();

		strRegionValue[0] = objRegions_page
				.getRegionValue(objLogin_data.strRegionStatewideFlorida);

		strRegionValue[1] = objRegions_page
				.getRegionValue(objLogin_data.strRegionName4);

		objNavigationToSubmenus.navigateToStatusTypesInSetup();

		// RoleBased Status Types in Region1// TST1
		objStatusTypeList
				.clickCreateNewStatusTypeButton()
				.selectStatusType(objStatuTypes_data.strNumberStatusType)
				.clickNextButton()
				.enterStatusTypeName(objStatuTypes_data.strNSTStatusTypeName)
				.enterStatusTypeDescription(
						objStatuTypes_data.strStatusDescription)
				.selectStandardStatusTypename(
						objStatuTypes_data.strStandardStatusTypename);

		strStdStatusValue[0] = objStatusTypeList
				.getStandardStatusValue(objStatuTypes_data.strStandardStatusTypename);

		System.out.println(strStdStatusValue[0]);

		objStatusTypeList.clickOnSaveButton();

		strstatusTypeValues[0] = objStatusTypeList
				.getStatusValue(objStatuTypes_data.strNSTStatusTypeName);
		
		// TST2
		objStatusTypeList
				.clickCreateNewStatusTypeButton()
				.selectStatusType(objStatuTypes_data.strNumberStatusType)
				.clickNextButton()
				.enterStatusTypeName(objStatuTypes_data.strNSTStatusTypeName1)
				.enterStatusTypeDescription(
						objStatuTypes_data.strStatusDescription)
				.selectStandardStatusTypename(
						objStatuTypes_data.strStandardStatusTypename);

		strStdStatusValue[0] = objStatusTypeList
				.getStandardStatusValue(objStatuTypes_data.strStandardStatusTypename);

		System.out.println(strStdStatusValue[0]);

		objStatusTypeList.clickOnSaveButton();

		strstatusTypeValues1[0] = objStatusTypeList
				.getStatusValue(objStatuTypes_data.strNSTStatusTypeName1);

		// Resource type creation in Region1
		objResourceType.navigateToResourceTypePage().createResourceType(
				objResourceType_data.strResourceTypeName, strstatusTypeValues);

		strResourceTypeValue[0] = objResourceType
				.getResourceTypeValue(objResourceType_data.strResourceTypeName);

		// create Resource in Region1
		objResource
				.navigateToResourceListPage()
				.clickOnCreateNewResourceButton()
				.enterResourceName(objResource_data.strResourceName)
				.enterResourceAbbrivation(
						objResource_data.strResourceAbbrivation)
				.selectResourceTypename(
						objResourceType_data.strResourceTypeName)
				.selectStandardResourceTypename(
						objResource_data.strStandardResourceTypename1)
				.enterResourceFirstName(objResource_data.strResourceFirstName)
				.enterResourceLastName(objResource_data.strResourceLastName)
				.enterStreetAddress(objResource_data.strStreetAddress)
				.selectState(objResource_data.strState)
				.enterCity(objResource_data.strCity)
				.enterzipCode(objResource_data.strZipcode)
				.selectCounty(objResource_data.strCounty)
				.clickOnLookupAddressBtn().verMap();

		String strLatitude = objResource.getLatitude();
		String strLogitude = objResource.getLongitude();

		strStdResourceValue[0] = objResource
				.getStandardResourceValue(objResource_data.strStandardResourceTypename1);
		
		objResource.clickOnSaveButton().clickOnViewResChkBox()
				.clickOnSaveButton();
		
		objResource.clickOnStatusTypeLinkInResourcePage(objResource_data.strResourceName)
		.selectStatusType(strstatusTypeValues1).clickOnSaveButton();
		
		// Create role
		objNavigationToSubmenus.navigateToRoles();

		objRoles.clickOnCreateNewRoleBtn()
				.enterRoleName(objRolesData.strRoleName1)
				.clickStatusTypeInRoleMayViewSection(strstatusTypeValues)
				.clickStatusTypeInRoleMayUpdateSection(strstatusTypeValues)
				.clickStatusTypeInRoleMayViewSection(strstatusTypeValues1)
				.clickStatusTypeInRoleMayUpdateSection(strstatusTypeValues1);
		objUsersList.selectReportStatewideResourceDetail();
		objRoles.clickOnSaveBtn();

		strRoleValue[0] = objRoles.getRoleValue(objRolesData.strRoleName1);
		
		// User creation
		objUsersList
				.navigateToUsersNew()
				.clickCreateNewUserButton()
				.enterUserDetails(objUserdata.strNewUserName,
						objUserdata.strNewPassword, objUserdata.strFullName)
				.selectRoleCheckBox(strRoleValue[0])
				.selectViewResourceRights(objResource_data.strResourceName)
				.selectUpdateStatusOfResource(objResource_data.strResourceName)
				.clickSaveButton()
				.searchUserName(objUserdata.strNewUserName,
						objUserdata.strRole, objUserdata.strResourceType,
						objUserdata.strUsername, objUserdata.strsearchOption)
				.clickRegionsLinkForUser(objUserdata.strNewUserName)
				.selectRegion(strRegionValue[1]).clickSaveButton();
		
		System.out.println(objUserdata.strNewUserName);

		//Another region
		objSelectRegion.selectRegionAndNavigate(objLogin_data.strRegionName4
				.trim());

		objRegionDefault.selectFrame();

		objNavigationToSubmenus.navigateToStatusTypesInSetup();

		// RoleBased Status Types in Region2
		objStatusTypeList
				.clickCreateNewStatusTypeButton()
				.selectStatusType(objStatuTypes_data.strNumberStatusType)
				.clickNextButton()
				.enterStatusTypeName(objStatuTypes_data.strNSTStatusTypeName2)
				.enterStatusTypeDescription(
						objStatuTypes_data.strStatusDescription)
				.selectStandardStatusTypename(
						objStatuTypes_data.strStandardStatusTypename);

		strStdStatusValueInReg2[0] = objStatusTypeList
				.getStandardStatusValue(objStatuTypes_data.strStandardStatusTypename);

		objStatusTypeList.clickOnSaveButton();

		strstatusTypeValuesInReg2[0] = objStatusTypeList
				.getStatusValue(objStatuTypes_data.strNSTStatusTypeName2);

		// Resource type creation in Region1
		objResourceType.navigateToResourceTypePage().createResourceType(
				objResourceType_data.strResourceTypeName1,
				strstatusTypeValuesInReg2);

		strResourceTypeValueInReg2[0] = objResourceType
				.getResourceTypeValue(objResourceType_data.strResourceTypeName1);

		// create Resource in Region2
		objResource
				.navigateToResourceListPage()
				.clickOnCreateNewResourceButton()
				.enterResourceName(objResource_data.strResourceName1)
				.enterResourceAbbrivation(
						objResource_data.strResourceAbbrivation)
				.selectResourceTypename(
						objResourceType_data.strResourceTypeName1)
				.selectStandardResourceTypename(
						objResource_data.strStandardResourceTypename)
				.enterResourceFirstName(objResource_data.strResourceFirstName)
				.enterResourceLastName(objResource_data.strResourceLastName)
				.enterStreetAddress(objResource_data.strStreetAddress)
				.selectState(objResource_data.strState)
				.enterCity(objResource_data.strCity)
				.enterzipCode(objResource_data.strZipcode)
				.selectCounty(objResource_data.strCounty)
				.clickOnLookupAddressBtn().verMap();

		String strLatitudeInReg2 = objResource.getLatitude();
		String strLogitudeInReg2 = objResource.getLongitude();

		strStdResourceValueInReg2[0] = objResource
				.getStandardResourceValue(objResource_data.strStandardResourceTypename);

		objResource.clickOnSaveButton().clickOnViewResChkBox()
				.clickOnSaveButton();

		objLogin.clickLogOut();

		System.out.println("-----Precondition ends and test execution starts-------");

		objLogin1.loginAsNewUser(objUserdata.strNewUserName,
				objUserdata.strNewPassword);

		objSelectRegion1.selectRegionAndNavigate(objLogin_data.strRegionStatewideFlorida);

		objRegionDefault1.selectFrame();

		objNavigationToSubMenus1.navigateToMap();

		objMap.selectResourceNameInFindResourceDropdown(
				objResource_data.strResourceName)
				.verUpdateStatusInPopupWindow()
				.clickUpdateStatusInPopupWindow();

		objUpdateStatus
				.selectStatusTypes(strstatusTypeValues[0])
				.enterNSTAndTSTUpdateValue(strstatusTypeValues[0],
						objView_data.strValueForUpdate)
				.selectStatusTypes(strstatusTypeValues1[0])
				.enterNSTAndTSTUpdateValue(strstatusTypeValues1[0],
						objView_data.strValueForUpdate1).clickOnSaveButton();
		
		//Generate Report
		objNavigationToSubMenus1.clickOnResourceReports();

		objReport1.verifyResourceReportMenuPage()
				.clickOnStatewideResourceDetails()
				.verifyStatewideResourceDetailReportPage()
				.selectStandardResources(strStdResourceValue)
				.selectStandardResources(strStdResourceValueInReg2)
				.clickOnNextButtonInResourceDetailPage()
				.selectStandardStatus(strStdStatusValue)
				.clickOnGenerateReportBtn();

		Thread.sleep(20000);
		objAutoIT.DownloadTheReports(strAutoItPath, strDownloadName,
				strAutoITName);
		int intCount = 0;
		int intCount1 = 0;
		do {

			try {
				assertTrue(new File(strDownloadName).exists());
				Thread.sleep(10000);
				Runtime.getRuntime().exec(
						"wscript " + autoItFiles + filePath + " "
								+ strCSVFileNameRenamed);

				intCount1 = 0;
				do {
					try {
						assertTrue(new File(strCSVDownlRenamedPath).exists());
						break;
					} catch (AssertionError Ae) {
						Thread.sleep(1000);
						intCount1++;
					}

				} while (intCount1 < 60);

				break;
			} catch (AssertionError Ae) {
				Thread.sleep(1000);
				intCount++;
			}
		} while (intCount < 60);
		
		String strValue = objOffCommonFunc.readInfoExcel(
				"Statewide Resource Detail Repor", 1, 1, strDownloadName1);
		assertEquals(objReport_data.strStatewideResourceDetailReport, strValue);

		int intRowCount = objOffCommonFunc.getRowsCountOfExceSheet(
				strDownloadName1, "Statewide Resource Detail Repor");

		String[] strHeaderNames = objReport_data.StatewideReportHeaders;

		String[] strAnswers = {
				objLogin_data.strRegionStatewideFlorida,
				objResource_data.strResourceName,
				objResourceType_data.strResourceTypeName,
				objResource_data.strStreetAddress + ", "
						+ objResource_data.strCity + ", "
						+ objResource_data.strCaliforniaCode + " "
						+ objResource_data.strZipcode + "",
				objResource_data.strCounty, strLogitude, strLatitude, "", "",
				"", "", "FN LN", "", "", "", "", "", "3" };

		String[] strAnswers2 = {
				objLogin_data.strRegionName4,
				objResource_data.strResourceName1,
				objResourceType_data.strResourceTypeName1,
				objResource_data.strStreetAddress + ", "
						+ objResource_data.strCity + ", "
						+ objResource_data.strCaliforniaCode + " "
						+ objResource_data.strZipcode + "",
				objResource_data.strCounty, strLogitudeInReg2,
				strLatitudeInReg2, "", "", "", "", "FN LN", "", "", "", "", "",
				"" };

		for (int i = 1; i <= strHeaderNames.length; i++) {
			strValue = objOffCommonFunc.readInfoExcel(
					"Statewide Resource Detail Repor", 2, i, strDownloadName1);
			assertEquals(strHeaderNames[i - 1], strValue);
		}
		System.out.println(objResource_data.strResourceName);
		System.out.println(objResource_data.strResourceName1);

		String strRes1 = objResource_data.strResourceName;
		String strRes2 = objResource_data.strResourceName1;

		int intcnt = 0;
		for (int i = intRowCount; i <= intRowCount; i--) {
			if (i != 0) {
				strValue = objOffCommonFunc.readInfoExcel(
						"Statewide Resource Detail Repor", i, 2,
						strDownloadName1);
				if (strValue.contains(strRes1) || strValue.contains(strRes2)) {
					for (int j = 1; j <= strAnswers.length; j++) {
						strValue = objOffCommonFunc.readInfoExcel(
								"Statewide Resource Detail Repor", i, j,
								strDownloadName1);
						assertTrue(strValue.contains(strAnswers[j - 1])
								|| strValue.contains(strAnswers2[j - 1]));
					}
					intcnt++;
				}
			}
			if (intcnt == 2)
				break;
		}

		gstrResult = "PASS";
	}

	/******************************************************************************************
	'Description : Verify that for a multi status types created with same standard statuses the
	                updates are displayed appropriately in the report generated. 
	'Date	 	 : 9-Feb-2016
	'Author		 : Anitha
	'------------------------------------------------------------------------------------------
	'Modified Date			                        	Modified By
	'Date					                            Name
	********************************************************************************************/
	@Test(description = " 	Verify that for a multi status types created with same standard statuses "
			+ "the updates are displayed appropriately in the report generated. ")
	public void testHappyDay99556() throws Exception {

		gstrTCID = "99556";
		gstrTO = " 	Verify that for a multi status types created with same standard statuses the updates"
				+ " are displayed appropriately in the report generated. ";

		Login_data objLogin_data = new Login_data();
		ResourceType_data objResourceType_data = new ResourceType_data();
		Resource_data objResource_data = new Resource_data();
		StatusTypes_data objStatuTypes_data = new StatusTypes_data();
		Report_data objReport_data = new Report_data();
		User_data objUserdata = new User_data();
		PathsProperties objAP = new PathsProperties();
		Roles_data objRolesData = new Roles_data();
		Properties pathProps = objAP.ReadAutoit_FilePath();
		Date_Time_settings dts = new Date_Time_settings();
		OfficeCommonFunctions objOffCommonFunc = new OfficeCommonFunctions();

		String strTimeText = dts.getCurrentDate(objReport_data.dateFormat1);
		String fileType = objReport_data.reportFile;
		Login objLogin = new Login(this.driver1);
		UsersList objUsersList = new UsersList(this.driver1);
		Roles objRoles = new Roles(this.driver1);
		SelectRegion objSelectRegion = new SelectRegion(this.driver1);
		RegionDefault objRegionDefault = new RegionDefault(this.driver1);
		StatusTypeList objStatusTypeList = new StatusTypeList(this.driver1);
		ResourceType objResourceType = new ResourceType(this.driver1);
		Resource objResource = new Resource(this.driver1);
		Regions objRegions_page = new Regions(this.driver1);
		NavigationToSubMenus objNavigationToSubmenus = new NavigationToSubMenus(
				this.driver1);

		AutoIT objAutoIT = new AutoIT(this.driver1);
		Report objReport1 = new Report(this.driver1);
		Map objMap = new Map(this.driver1);
		Login objLogin1 = new Login(this.driver1);
		SelectRegion objSelectRegion1 = new SelectRegion(this.driver1);
		RegionDefault objRegionDefault1 = new RegionDefault(this.driver1);
		UpdateStatus objUpdateStatus = new UpdateStatus(this.driver1);
		NavigationToSubMenus objNavigationToSubMenus1 = new NavigationToSubMenus(
				this.driver1);

		String strstatusTypeValues[] = new String[1];
		String strstatusTypeValues1[] = new String[1];
		String strStdStatusValue[] = new String[1];
		String strStdResourceValue[] = new String[1];
		String strResourceTypeValue[] = new String[1];
		String strRoleValue[] = new String[1];
		String strRegionValue[] = new String[2];
		String strStatusesValues[] = new String[2];

		String strstatusTypeValuesInReg2[] = new String[1];
		String strStdStatusValueInReg2[] = new String[1];
		String strResourceTypeValueInReg2[] = new String[1];
		String strStdResourceValueInReg2[] = new String[1];
		String strStatusesValuesInReg2[] = new String[1];

		String AutoIT_FILE_PATH = objReport_data.reportsDownloadAutoItPath;
		String strAutoItPath = ReadAutoItProperty
				.readDataFromAutoItPath(AutoIT_FILE_PATH);
		String strAutoITName = pathProps
				.getProperty(objReport_data.reportsDownloadAutoItName);
		String fileDownloadPath = pathProps
				.getProperty(objReport_data.reportsDownloadPath);

		String autoItFilesPath = pathProps
				.getProperty(objReport_data.autoItPath);

		File file = new File(System.getProperty("user.dir") + fileDownloadPath);

		File autoItFiles = new File(System.getProperty("user.dir")
				+ autoItFilesPath);

		String strDownloadName = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + fileType;
		String strCSVFileNameRenamed = "TC" + gstrTCID + "_" + strTimeText;

		String strCSVDownlRenamedPath = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + objReport_data.xlsFile;

		String strDownloadName1 = file + "\\" + "TC" + gstrTCID + "_"
				+ strTimeText + objReport_data.xlsFile;

		String filePath = file + "\\";

		objLogin.loginToApplication(objLogin_data.strUserName,
				objLogin_data.strPassword);

		objSelectRegion.selectRegionAndNavigate(objLogin_data.strRegionStatewideFlorida);

		objRegionDefault.selectFrame();

		objNavigationToSubmenus.navigateToRegions();

		strRegionValue[0] = objRegions_page
				.getRegionValue(objLogin_data.strRegionStatewideFlorida);

		strRegionValue[1] = objRegions_page
				.getRegionValue(objLogin_data.strRegionName4);

		objNavigationToSubmenus.navigateToStatusTypesInSetup();

		// RoleBased Status Types in Region1// MST1
		objStatusTypeList
				.clickCreateNewStatusTypeButton()
				.selectStatusType(objStatuTypes_data.strMultiStatusType)
				.clickNextButton()
				.enterStatusTypeName(objStatuTypes_data.strMSTStatusTypeName)
				.enterStatusTypeDescription(
						objStatuTypes_data.strStatusDescription)
				.selectStandardStatusTypename(
						objStatuTypes_data.strStandardStatusTypeName4);
		strStdStatusValue[0] = objStatusTypeList
				.getStandardStatusValue(objStatuTypes_data.strStandardStatusTypeName4);
		System.out.println(strStdStatusValue[0]);
		objStatusTypeList
				.clickOnSaveButton()
				.clickOnCreateNewStatus()
				.enterStatusName(objStatuTypes_data.strStatusNameInMulti)
				.clickOnSaveButton()
		   
		.createNewStatus(objStatuTypes_data.strStatusNameInMulti2,
				objStatuTypes_data.strStatusColor)
		.verCreatedStatusInStatusListForMulti(
					  objStatuTypes_data.strStatusNameInMulti2);

		strStatusesValues[0] = objStatusTypeList
				.getStatusesValue(objStatuTypes_data.strStatusNameInMulti);

		objStatusTypeList.clickOnReturnToStatusTypeList();
		
		strstatusTypeValues[0] = objStatusTypeList
				.getStatusValue(objStatuTypes_data.strMSTStatusTypeName);
		
		// MST2
		objStatusTypeList
				.clickCreateNewStatusTypeButton()
				.selectStatusType(objStatuTypes_data.strMultiStatusType)
				.clickNextButton()
				.enterStatusTypeName(objStatuTypes_data.strMSTStatusTypeName1)
				.enterStatusTypeDescription(
						objStatuTypes_data.strStatusDescription)
				.selectStandardStatusTypename(
						objStatuTypes_data.strStandardStatusTypeName4);

		strStdStatusValue[0] = objStatusTypeList
				.getStandardStatusValue(objStatuTypes_data.strStandardStatusTypeName4);
		System.out.println(strStdStatusValue[0]);

		objStatusTypeList.clickOnSaveButton().clickOnCreateNewStatus()
				.enterStatusName(objStatuTypes_data.strStatusNameInMulti1)
				.clickOnSaveButton()
				
		.createNewStatus(objStatuTypes_data.strStatusNameInMulti2,
				objStatuTypes_data.strStatusColor)
		.verCreatedStatusInStatusListForMulti(
					  objStatuTypes_data.strStatusNameInMulti2);

		strStatusesValues[1] = objStatusTypeList
				.getStatusesValue(objStatuTypes_data.strStatusNameInMulti1);

		objStatusTypeList.clickOnReturnToStatusTypeList();

		strstatusTypeValues1[0] = objStatusTypeList
				.getStatusValue(objStatuTypes_data.strMSTStatusTypeName1);

		// Resource type creation in Region1
		objResourceType.navigateToResourceTypePage().createResourceType(
				objResourceType_data.strResourceTypeName, strstatusTypeValues);

		strResourceTypeValue[0] = objResourceType
				.getResourceTypeValue(objResourceType_data.strResourceTypeName);

		// create Resource in Region1
		objResource
				.navigateToResourceListPage()
				.clickOnCreateNewResourceButton()
				.enterResourceName(objResource_data.strResourceName)
				.enterResourceAbbrivation(
						objResource_data.strResourceAbbrivation)
				.selectResourceTypename(
						objResourceType_data.strResourceTypeName)
				.selectStandardResourceTypename(
						objResource_data.strStandardRTHomeHealth)
				.enterResourceFirstName(objResource_data.strResourceFirstName)
				.enterResourceLastName(objResource_data.strResourceLastName)
				.enterStreetAddress(objResource_data.strStreetAddress)
				.selectState(objResource_data.strState)
				.enterCity(objResource_data.strCity)
				.enterzipCode(objResource_data.strZipcode)
				.selectCounty(objResource_data.strCounty)
				.clickOnLookupAddressBtn().verMap();

		String strLatitude = objResource.getLatitude();
		String strLogitude = objResource.getLongitude();

		strStdResourceValue[0] = objResource
				.getStandardResourceValue(objResource_data.strStandardRTHomeHealth);
		
		objResource.clickOnSaveButton().clickOnViewResChkBox()
				.clickOnSaveButton();
		
		objResource.clickOnStatusTypeLinkInResourcePage(objResource_data.strResourceName)
		.selectStatusType(strstatusTypeValues1).clickOnSaveButton();
		
		// Create role
		objNavigationToSubmenus.navigateToRoles();

		objRoles.clickOnCreateNewRoleBtn()
				.enterRoleName(objRolesData.strRoleName1)
				.clickStatusTypeInRoleMayViewSection(strstatusTypeValues)
				.clickStatusTypeInRoleMayUpdateSection(strstatusTypeValues)
				.clickStatusTypeInRoleMayViewSection(strstatusTypeValues1)
				.clickStatusTypeInRoleMayUpdateSection(strstatusTypeValues1);
		objUsersList.selectReportStatewideResourceDetail();
		objRoles.clickOnSaveBtn();

		strRoleValue[0] = objRoles.getRoleValue(objRolesData.strRoleName1);
		
		// User creation
		objUsersList
				.navigateToUsersNew()
				.clickCreateNewUserButton()
				.enterUserDetails(objUserdata.strNewUserName,
						objUserdata.strNewPassword, objUserdata.strFullName)
				.selectRoleCheckBox(strRoleValue[0])
				.selectViewResourceRights(objResource_data.strResourceName)
				.selectUpdateStatusOfResource(objResource_data.strResourceName)
				.clickSaveButton()
				.searchUserName(objUserdata.strNewUserName,
						objUserdata.strRole, objUserdata.strResourceType,
						objUserdata.strUsername, objUserdata.strsearchOption)
				.clickRegionsLinkForUser(objUserdata.strNewUserName)
				.selectRegion(strRegionValue[1]).clickSaveButton();
		
		System.out.println(objUserdata.strNewUserName);

		//Another region
		objSelectRegion.selectRegionAndNavigate(objLogin_data.strRegionName4
				.trim());

		objRegionDefault.selectFrame();

		objNavigationToSubmenus.navigateToStatusTypesInSetup();

		// RoleBased Status Types in Region2
		objStatusTypeList
				.clickCreateNewStatusTypeButton()
				.selectStatusType(objStatuTypes_data.strMultiStatusType)
				.clickNextButton()
				.enterStatusTypeName(objStatuTypes_data.strMSTStatusTypeName2)
				.enterStatusTypeDescription(
						objStatuTypes_data.strStatusDescription)
				.selectStandardStatusTypename(
						objStatuTypes_data.strStandardStatusTypeName4);

		strStdStatusValueInReg2[0] = objStatusTypeList
				.getStandardStatusValue(objStatuTypes_data.strStandardStatusTypeName4);

		objStatusTypeList.clickOnSaveButton().clickOnCreateNewStatus()
				.enterStatusName(objStatuTypes_data.strStatusNameInMulti)
				.clickOnSaveButton();

		strStatusesValuesInReg2[0] = objStatusTypeList
				.getStatusesValue(objStatuTypes_data.strStatusNameInMulti);
		
		objStatusTypeList
		.createNewStatus(objStatuTypes_data.strStatusNameInMulti1,
				objStatuTypes_data.strStatusColor)
		.verCreatedStatusInStatusListForMulti(
					  objStatuTypes_data.strStatusNameInMulti1);

		objStatusTypeList.clickOnReturnToStatusTypeList();

		strstatusTypeValuesInReg2[0] = objStatusTypeList
				.getStatusValue(objStatuTypes_data.strMSTStatusTypeName2);

		// Resource type creation in Region1
		objResourceType.navigateToResourceTypePage().createResourceType(
				objResourceType_data.strResourceTypeName1,
				strstatusTypeValuesInReg2);

		strResourceTypeValueInReg2[0] = objResourceType
				.getResourceTypeValue(objResourceType_data.strResourceTypeName1);

		// create Resource in Region2
		objResource
				.navigateToResourceListPage()
				.clickOnCreateNewResourceButton()
				.enterResourceName(objResource_data.strResourceName1)
				.enterResourceAbbrivation(
						objResource_data.strResourceAbbrivation)
				.selectResourceTypename(
						objResourceType_data.strResourceTypeName1)
				.selectStandardResourceTypename(
						objResource_data.strStandardResourceTypename2)
				.enterResourceFirstName(objResource_data.strResourceFirstName)
				.enterResourceLastName(objResource_data.strResourceLastName)
				.enterStreetAddress(objResource_data.strStreetAddress)
				.selectState(objResource_data.strState)
				.enterCity(objResource_data.strCity)
				.enterzipCode(objResource_data.strZipcode)
				.selectCounty(objResource_data.strCounty)
				.clickOnLookupAddressBtn().verMap();

		String strLatitudeInReg2 = objResource.getLatitude();
		String strLogitudeInReg2 = objResource.getLongitude();

		strStdResourceValueInReg2[0] = objResource
				.getStandardResourceValue(objResource_data.strStandardResourceTypename2);

		objResource.clickOnSaveButton().clickOnViewResChkBox()
				.clickOnSaveButton();

		objLogin.clickLogOut();

		System.out.println("-----Precondition ends and test execution starts-------");

		objLogin1.loginAsNewUser(objUserdata.strNewUserName,
				objUserdata.strNewPassword);

		objSelectRegion1.selectRegionAndNavigate(objLogin_data.strRegionStatewideFlorida);

		objRegionDefault1.selectFrame();

		objNavigationToSubMenus1.navigateToMap();

		objMap.selectResourceNameInFindResourceDropdown(
				objResource_data.strResourceName)
				.verUpdateStatusInPopupWindow()
				.clickUpdateStatusInPopupWindow();

		objUpdateStatus
				.selectStatusTypes(strstatusTypeValues[0])
				.selectMSTUpdateValue(strstatusTypeValues[0],
						strStatusesValues[0])
				.selectStatusTypes(strstatusTypeValues1[0])
				.selectMSTUpdateValue(strstatusTypeValues1[0],
						strStatusesValues[1]).clickOnSaveButton();
		
		//Generate Report
		objNavigationToSubMenus1.clickOnResourceReports();

		objReport1.verifyResourceReportMenuPage()
				.clickOnStatewideResourceDetails()
				.verifyStatewideResourceDetailReportPage()
				.selectStandardResources(strStdResourceValue)
				.selectStandardResources(strStdResourceValueInReg2)
				.clickOnNextButtonInResourceDetailPage()
				.selectStandardStatus(strStdStatusValue)
				.clickOnGenerateReportBtn();

		Thread.sleep(20000);
		objAutoIT.DownloadTheReports(strAutoItPath, strDownloadName,
				strAutoITName);
		int intCount = 0;
		int intCount1 = 0;
		do {

			try {
				assertTrue(new File(strDownloadName).exists());
				Thread.sleep(10000);
				Runtime.getRuntime().exec(
						"wscript " + autoItFiles + filePath + " "
								+ strCSVFileNameRenamed);

				intCount1 = 0;
				do {
					try {
						assertTrue(new File(strCSVDownlRenamedPath).exists());
						break;
					} catch (AssertionError Ae) {
						Thread.sleep(1000);
						intCount1++;
					}

				} while (intCount1 < 60);

				break;
			} catch (AssertionError Ae) {
				Thread.sleep(1000);
				intCount++;
			}
		} while (intCount < 60);
		
		String strValue = objOffCommonFunc.readInfoExcel(
				"Statewide Resource Detail Repor", 1, 1, strDownloadName1);
		assertEquals(objReport_data.strStatewideResourceDetailReport, strValue);

		int intRowCount = objOffCommonFunc.getRowsCountOfExceSheet(
				strDownloadName1, "Statewide Resource Detail Repor");

		String[] strHeaderNames = { "Region", "Resource Name", "Type",
				"Address", "County", "Latitude", "Longitude", "EMResource ID",
				"AHA ID", "External ID", "Website", "Contact", "Phone 1",
				"Phone 2", "Fax", "Email", "Notes", "FL: Active" };

		String[] strAnswers = {
				objLogin_data.strRegionStatewideFlorida,
				objResource_data.strResourceName,
				objResourceType_data.strResourceTypeName,
				objResource_data.strStreetAddress + ", "
						+ objResource_data.strCity + ", "
						+ objResource_data.strCaliforniaCode + " "
						+ objResource_data.strZipcode + "",
				objResource_data.strCounty, strLogitude, strLatitude, "", "",
				"", "", "FN LN", "", "", "", "", "", ""+objStatuTypes_data.strStatusNameInMulti+""
						+ "; "+objStatuTypes_data.strStatusNameInMulti+"" };

		String[] strAnswers2 = {
				objLogin_data.strRegionName4,
				objResource_data.strResourceName1,
				objResourceType_data.strResourceTypeName1,
				objResource_data.strStreetAddress + ", "
						+ objResource_data.strCity + ", "
						+ objResource_data.strCaliforniaCode + " "
						+ objResource_data.strZipcode + "",
				objResource_data.strCounty, strLogitudeInReg2,
				strLatitudeInReg2, "", "", "", "", "FN LN", "", "", "", "", "",
				"" };

		for (int i = 1; i <= strHeaderNames.length; i++) {
			strValue = objOffCommonFunc.readInfoExcel(
					"Statewide Resource Detail Repor", 2, i, strDownloadName1);
			assertEquals(strHeaderNames[i - 1], strValue);
		}
		System.out.println(objResource_data.strResourceName);
		System.out.println(objResource_data.strResourceName1);

		String strRes1 = objResource_data.strResourceName;
		String strRes2 = objResource_data.strResourceName1;
		System.out.println(strAnswers);
		System.out.println(strAnswers2);

		int intcnt = 0;
		for (int i = intRowCount; i <= intRowCount; i--) {
			if (i != 0) {
				strValue = objOffCommonFunc.readInfoExcel(
						"Statewide Resource Detail Repor", i, 2,
						strDownloadName1);
				if (strValue.contains(strRes1) || strValue.contains(strRes2)) {
					for (int j = 1; j <= strAnswers.length; j++) {
						strValue = objOffCommonFunc.readInfoExcel(
								"Statewide Resource Detail Repor", i, j,
								strDownloadName1);
						assertTrue(strValue.contains(strAnswers[j - 1])
								|| strValue.contains(strAnswers2[j - 1]));
					}
					intcnt++;
				}
			}
			if (intcnt == 2)
				break;
		}

		gstrResult = "PASS";
	}
}
