package EMR.Locators;

public class EventManagement {

	public static class Locators {

		public static final String  CREATENEWEVENT 				= "input[value='Create New Event']",
				EVENTMANAGEMENTTABLE 							= "//div[@id='mainContainer']/table/tbody/tr",
				EVENTNAME 										= "title",
				EVENTDESCRIPTION 								= "description",
				SAVE 											= "input[value='Save']",
				ACKNOWLWDGENOTIFICATION 						= "//button[text()='Acknowledge All Notifications']",
				WEBNOTIFICATIONFRAME 							= "TB_iframeContent",
				HEADEROFNOTIFICATION 							= "dt.othr",
				DESCRIPTIONOFNOTIFICATION 						= "dd.desc",
				PARTICIPATINGRESOURCEINPUTPART1 				= "//td[text()='",
				PARTICIPATINGRESOURCEINPUTPART2 				= "/preceding-sibling::td/input",
				TABLECELL 										= "/td[text()='",
				ENDEVENTPART2 									= "']/preceding-sibling::td[6]/a[text()='End']",
				EVENTTEMPLATEPART2 								= "']/preceding-sibling::td[text()='",
				EVENTTEMPLATEPART3 								= "']/preceding-sibling::td/a[text()='",
				CLOSEBRACKETS 									= "']",
				TABLECELLWITHTEXT 								= "//td[text()='",
				CREATENEWMULTIREGIONEVENT						= "input[value='Create New Multi-Region Event']",
				CLOSING_BRACKET									= "']",
				PARTICIPATING_REGION_PART1 						= "/following-sibling::td/select",
				NEXT											= "input[value='Next']",
				MULTIREGIONEVENTCONFIRMATION					= "//h1[text()='Multi-Region Event Confirmation']",
				YES												= "input[value='Yes']",
				STREET_ADDRESS									= "streetAddress",
				CITY											= "city",
				STATE											= "stateAbbrev",
				ZIPCODE											= "zipCode",
				EVENT_START_MONTH								= "startMonth",
				EVENT_START_DAY									= "startDay",
				EVENT_START_YEAR								= "startYear",
				EVENT_START_HOUR								= "startHour",
				EVENT_START_MINUTE								= "startMinute",
				GET_EVENT_START_MONTH 							= "//select[@name='startMonth']/option[@selected]",
				GET_EVENT_START_DAY								= "//select[@name='startDay']/option[@selected]",
				GET_EVENT_START_YEAR  							= "//select[@name='startYear']/option[@selected]",
				GET_EVENT_START_HOUR  							= "//select[@name='startHour']/option[@selected]",
				GET_EVENT_START_MINUTE  						= "//select[@name='startMinute']/option[@selected]",
				KEEP_BUTTON										= "input[value='Keep']",
				PRECEDING_COLOUMN_OF_TITLE						= "/preceding-sibling::td[text()='",
				FOLLOWING_COLOUMN_OF_TITLE						= "/following-sibling::td[text()='",
				CREATEMULTIREGIONEVENTPAGE						= "//h1[text()='Create Multi-Region Event']",
				EVENT_MANAGEMENT								= "//h1[text()='Event Management']",
				COUNTY											= "county",
				EVENTSTART_IMMEDIATELY							= "//tr/td[text()='Immediately']/input[@value='Y']",
				EVENTSTART_DATE									= "//tr/td[text()='Immediately']/input[@value='N']",
				EVENTEND_HOUR									= "//tr/td/input[@value='HOURS']",
				EVENTEND_DATE									= "input[value='DATE']",
				EVENTEND_NEVER									= "input[value='NEVER']",
				BROWSE_OPTION 									= "document",
				DISPLAY_IN_EVENT_BANNER 						= "displayInEventBanner",
				PRIVATE											= "privateEvent",
				DRILL											= "drill",
				END_QUIETLY										= "endQuietly",
				LATITUDE										= "latitude",
				LONGITUDE										= "longitude",
				LOOKUP_ADDRESS									= "input[value='Lookup Address']",
				VIEW_MAP										= "//tr/td/input[@value='View Map']",
				EVENT_NAME_IN_TABLE								= "//tr/td[text()='",
				EDIT_EVENT_NAME									= "/preceding-sibling::td/a[text()='Edit']",
				INCLUDE_ALL_RESOURCES_CHECKBOX					= "input[name='includeAllResources'][class='checkbox']",
				END_DATE										= "input[name='durationHours']",
				EVENT_IN_EVENT_BANNER_PART1						= "//div[@id='eventsBanner']/table//td/a[text()='",
				EVENT_STATUS_PAGE								= "//div[@id='topSubNav']/h1[text()='Event Status']",
				EVENT_END_MONTH									= "endMonth",
				EVENT_END_DAY									= "endDay",
				EVENT_END_YEAR									= "endYear",
				EVENT_END_HOUR									= "endHour",
				EVENT_END_MINUTE								= "endMinute",
				PARENT_COLUMN_OF_TITLE							= "/parent::tr/td[text()='",
				MULTI_REGION_EVENT_CONFIRMATION_MESSAGE			= "//strong",
				MODIFY_BUTTON									= "input[value='Modify']",
				TABLE_CELL_CONTAINS_CLASS						= "//td[contains(@class,'",
				CLOSING_BRACKET_WITH_QUOTE						= "')]",
				TABLE_CELL_CONTAINS_TEXT						= "/a[contains(@style,'",
				TEXT_FUNCTION									= "[text()='",
				DISPLAY_EVENT_BANNER_PART1						= "//div[@id='eventsBanner']/table[@class='events']//a[text()='",
				EVENT_IN_EVENT_BANNER_PART2						= "//div[@id='eventsBanner']/table//td[contains(@class,'",
				EVENT_ICON 										= "/preceding-sibling::td/img[contains(@src,'",
				CREATE_MULTIREGION_EVENT_OPTION					= "input[value='Create New Multi-Region Event']",
				INCLUDEALLRESOURCES								= "input[name='includeAllResources']",
				SELECTRESOURCEPAGEPART1							= "//h1[text()='Select Resources - ",
				RESOURCELISTPART1								= "//td[text()='",
				RESOURCELISTPART2								= "']/preceding-sibling::td[text()='",
				STATUSTYPEPAGE									= "//h1[text()='Select Status Types']",
				EDIT_MULTI_REGION_EVENT_PAGE					= "//h1[text()='Edit Multi-Region Event']",
				ALL_RESOURCE									= "input[name='SELECT_ALL']",
				CREATE_ADHOC_EVENT								= "input[value='Create Ad Hoc Event']",
				RESOURCEPAGE									= "//h1[text()='Select Resources']",
				PARTICIPATING_STATUSTYPE_INPUT_PART1 			= "//a[contains(text(),'",
				PARTICIPATING_STATUSTYPE_INPUT_PART2 			= "')]/parent::td/parent::tr/td/input[@name='statusTypeID']",
				STATUS_TYPE_VALUE								= "input[value='",
				AD_HOC_EVENT_CONFIRMATION_PAGE					= "//h1[text()='Ad Hoc Event Confirmation']",
				END_EVENT_HOUR 									= "input[value='HOURS']",
				TABLE_CELL_WITH_PRECEDING_SIBLING 				= "/preceding-sibling::td/a",
				SELECT_STATUS_TYPES                     		="input[name='st'][value='",
				EVENT_BANNER									= "//td/a[text()='",
				CANCEL											= "input[value='Cancel']",
			    SAVE_BUTTON_IN_BOTTOM_OF_PAGE 					= "//div[@id='mainContainer']/form/table/tbody/tr[20]/td/input[@value='Save']",
			    SAVE_BUTTON_IN_TOP_OF_PAGE						= "//div[@id='mainContainer']/form/table/tbody/tr[1]/td/input[@value='Save']",
				CANCEL_BUTTON_IN_TOP_OF_PAGE            		= "//div[@id='mainContainer']/form/table/tbody/tr[1]/td/input[@value='Cancel']",
				CANCEL_BUTTON_IN_BOTTOM_OF_PAGE					= "//div[@id='mainContainer']/form/table/tbody/tr[20]/td/input[@value='Cancel']",
				TABLE_HEADER_OF_EVENT_STATUS            		= "//th/a[text()='",
				RESOURCETYPE_AND_STATUSTYPES_UNDER_EVENT_STATUS	= "']/parent::th/following-sibling::th/a[text()='",
				CLOSING_BRACKETS 								= "']",
				SELECT_EVENT_TEMPLATE 							= "//h1[text()='Select Event Template']",
				CREATE_EVENT_PAGE 								= "//h1[text()='Create Event']",
				EVENT_LIST_PAGE 								= "//h1[text()='Event List']",
				ADDRESS_REQUIRED_ERROR_MESSAGE 					= "//div[@id='mainContainer']/div/span[text()='The following errors occurred on this page:']",
				NO_CITY_PROVIDED 								= "/parent::div/ul/li[text()='No city was provided.']",
				NO_STATE_PROVIDED 								= "/parent::div/ul/li[text()='No state was provided.']",
				NO_COUNTY_PROVIDED 								= "/parent::div/ul/li[text()='No county was provided.']",
				MANDATORY_SYMBOL								= "//span[@class='emsReqField'][text()='**']",
				CITY_MANDATORY 									= "/parent::td/following-sibling::td/input[@id='city']",
				STATE_MANDATORY 								= "/parent::td/following-sibling::td/select[@id='stateAbbrev']",
				COUNTY_MANDATORY 								= "/parent::td/following-sibling::td/select[@id='county']",
				SAVE_BUTTON_IN_BOTTOM_OF_PAGE_AFTER_EDIT 		= "//div[@id='mainContainer']/form/table/tbody/tr[22]/td/input[@value='Save']",
				CANCEL_BUTTON_IN_BOTTOM_OF_PAGE_AFTER_EDIT		= "//div[@id='mainContainer']/form/table/tbody/tr[22]/td/input[@value='Cancel']",
				EDIT_EVENT										= "//h1[text()='Edit Event']",
				EDIT_ADHOC_EVENT								= "//h1[text()='Edit Ad Hoc Event']",
				END_EVENT_NAME									= "/preceding-sibling::td/a[text()='End']",
				PREVIOUS_BUTTON									= "//input[@class='emsButtonText'][@value='Previous']",
				VALIDATION_MSG_FOR_EVENTBANNER					= "//div[@id='mainContainer']/div/ul",
				EVENT_START_DATE		 						= "/preceding-sibling::td[2]",
				ADDRESS_ON_EVENT_BANNER 						= "//div[contains(@style,'block;')]",
				RESOURCE_TO_PARTICIPATE 						= "//td[text()='Resources to Participate in This Event:']/parent::tr/following-sibling::tr//td[text()='",
				RESOURCE_UNDER_EVENT_STATUS 					= "/ancestor::thead/following-sibling::tbody//a[text()='",
				PROTECTED_HEALTH_INFORMATION_TITLE 				= "//div[text()='Protected Health Information (PHI)']",
				CONTENT_IN_PROTECTED_HEALTH_INFORMATION 		= "//body",
				CLOSE_PROTECTED_HEALTH_INFORMATION 				= "//a[@id='TB_closeWindowButton']",
				PROTECTED_HEALTH_INFORMATION 					= "//a[text()='Protected Health Information (PHI)']",
				TABLE_CELL_WITH_TEXT 							= "/td[text()='",
				SELECT_CREATE_OF_EVENT_TEMPLATE 				= "/preceding-sibling::td/a[text()='Create']",
				CREATE_ADHOC_EVENT_SCREEN						= "//h1[text()='Create Ad Hoc Event']",
				EVENT_TEMPLATE_WITH_NOTIFICATION				= "/preceding-sibling::td/a[text()='Notifications']",
				EVENT_TEMPLATE_WITH_SECURITY					= "/preceding-sibling::td/a[text()='Security']",
				CANCEL_EVENT_NAME								= "/preceding-sibling::td/a[text()='Cancel']",
				EVENT_POSITION 									= "//table/thead/tr/th[",
				EVENT_HEADER_PART1 								= "][text()='",
				EVENT_HEADER_PART2 								= "]/a[text()='",
				EVENT_RENOTIFY_DISABLED 						= "//td[text()='Re-notify:']/parent::tr/td[text()='Disabled']/input[@value='0']",
				EVENT_RENOTIFY_EVERY_HOUR 						= "//td[text()='Re-notify:']/parent::tr/td/input[@value='1']",
				EVENT_RENOTIFY_AT_SPECIFIED_TIMES 				= "//td[text()='Re-notify:']/parent::tr/td/input[@value='2']",
				EVENT_ACTION 									= "//th[text()='Action']/ancestor::table",
				EVENT_TITLE 									= "//th/a[text()='Title']/ancestor::table",
				EVENT_ID										= "//div[@id='ed",
				VIEW_HISTORY_ON_EVENT_BANNER 					= "//a[text()='View History']";
		}
	}
