package EMR.Locators;

public class UpdateStatus {
	public static class Locators {
		public static final String CLOSEBRACKETS 	= "']",
				CLOSINGTWOBRACES 					= "')]",
				SELECTALL 							= "selectAll",
				NSTORTSTUPDATEINPUT 				= "status_value_",
				SAVEBUTTON 							= "input[value='Save']",
				UPDATESTATUSPAGE 					= "//div[@id='topSubNav']/h1[text()='Update Status']",
				MSTUPDATEVALUEPART1 				= "input[value='",
				MSTUPDATEVALUEPART2 				= "'][name='status_value_",
				EDBEDS 								= "#edBedsOccupied",
				LOBYPATIENT 						= "#lobbyPatients",
				AMBULANCEPATIENTS 					= "#ambulancePatients",
				ADMITSGENERAL 						= "#admitsGeneral",
                ADMITSICU							= "#admitsIcu",
                ONEONONEPATIENTS					= "#oneOnOnePatients",
                SHORTSTAFFRN						= "#shortStaffRn",
                EDBEDSASSGINED						= "#edBedsAssigned",
                LOBYCAPICITY						= "#lobbyCapacity",
                EDPATIENTS							= "#edPatients" ,
				EDADMITS							= "#edAdmits",
			    DOORTOBEDTIME						= "#lastDoorToBedTime",
			    CRITIACALCAREPATIENTS				= "#criticalCarePatients",
			    LONGESTADMIT						= "#longestEdAdmit",
			    EDNUMBER							= "#edNumber",
			    IPNUMBER							= "#ipNumber",
			    SAVE								= "input[value='Save']",
			    UPDATEKEY							= "//td/a[text()='",
			    UPADTEKEYPART1						= "/parent::td/preceding-sibling::td[@valign='middle']/a/img[@title='Update Status']",
			    UPDATEDVALUES						= "//td[@id='v_",
			    UPDATEDVALUESPART1					= "_",
			    UPDATEDVALUESPART2					= "'][text()='",
			    GETUPDATEDSATURATIONSCOREVALUE		= "//td/a[text()='",
			    GETUPDATEDSATURATIONSCOREVALUEPART1	= "/following::td[5]",
			    GETUPDATEDNEDOCSVALUEPART1			= "/following::td[4]",
			    GETUPDATEDSTATUSVALUEPART			= "/following::td[2]",
			    GETUPDATEDNUMBERVALUE				= "/following::td[1]",
			    GETUPDATEDTEXTVALUE					= "/following::td[3]",
			    GETUPDATEDDATEVALUE					= "/following::td[6]",
			    CALCULATE							= "input[value='Calculate']",
			    SHOW_ALL							= ".selectionLink.showAll>b",
			    WEBNOTIFIACTIONFRAME                = "dt.othr",
			    UPDATESTATUSCHANGEVALUE				= "//dl/dd[@class='desc'][text()='",
			    APPLICATIONTIME						= "#statusTime",
			    MST_UPDATED_VALUES					= "//td[contains(@id,'_",
			    STATUS_REASON 						= "[name='status_reason_id_",
			    UNDER_SCORE   						= "_" ,
			    UPDATED_RESONS_PART1				= "//td/a[text()='",
			    UPDATED_RESONS_PART2				= "']/following::td[contains(text(),'",
			    LAST_UPDATED_TIME 					= "td[id='t_",
			    FOLLOWING_ERROR_OCCURED_HEADER		= "//span[@class='emsErrorTitle'][text()='The following error occurred on this page:']",
			    ERROR_TEXT_TO_UPDATE_STATUS			= "//div[@id='mainContainer']/div[3]/ul/li",
			    UPDATED_VALUES						= "v_",
			    SELECT_SINGLE_STAUS_TYPE			="//input[@id='st_",
				RESOURCE_COLOR_PART1 				= "//span[text()='",
				RESOURCE_COLOR_PART2 				= "[contains(@style,'",
				CLEAR_ALL                           = "#clearAll>b",
				CALCULATED_NEDOCS_SCORE_PART1       = "//span[@id='saturationScoreDisplay",
				CALCULATED_NEDOCS_SCORE_PART2       = "[contains(text(),'",
				NEDOCS_CALCULATE_BUTTON_PART1       = "//div[@id='st_",
				NEDOCS_CALCULATE_BUTTON_PART2       = "section']/div/div/input[@value='Calculate']",
		        SATURATION_CALCULATE_BUTTON_PART1   = "//input[@onclick='recalcSatScore(",
		        SATURATION_CALCULATE_BUTTON_PART2   =")']",
		        CANCEL                              =".bttn.atten",
		        UNAUTHORIZED_TO_UPDATE_MESSAGE      ="//h2[text()='You are not authorized to update any statuses for this resource.']",
		        RETURN_TO_VIEW                      ="Return to View";
		
	}
}