package EMR.Locators;

public class StatusTypes {
	public static class Locators {
		public static final String CLOSEBRACKETS = "']",
				TABLECELLWITHTEXT 				= "//td[text()='",
				CREATENEWSTATUSTYPEBUTTON 		= "input[value='Create New Status Type']",
				SELECTTYPE 						= "statusValueCode",
				NEXTBUTTON 						= "input[class='emsButtonText'][value='Next']",
				STATUSTYPENAME 					= "statusTypeName",
				STATUSDESCRIPTION 				= "definition",
				SAVEBUTTON 						= "input[class='emsButtonText'][value='Save']",
				SHAREDSTATUSTYPE 				= "input[name='visibility'][value=SHARED]",
				EVENTSTATUSTYPE 				= "eventOnly",
				DISPLAYSUMMARYTOTALSCHECKBOX	= "displaySummaryTotals",
				CREATENEWSTATUS 				= "input[value='Create New Status']",
				STATUSESNAME 					= "statusName",
				STATUSCOLOR 					= "select[name='colorCode']",
				EVENTEXPIRATION 				= "//input[@name='timeoutCode'][@value='EXPIR']",
				EVENTEXPIRATIONINMIN 			= "timeoutMinutes",
				RETURNTOSTATUSTYPELIST 			= "Return to Status Type List",
				SHIFTTIME 						= "input[name='shift'][value='1']",
				SHIFTTIMEHOUR 					= "select[name='expireHour1']",
				SHIFTTIMEMIN 					= "select[name='expireMin1']",
				GROUPLISTSELECT 				= "groupListSelect",
				STATUS 							= "//tr/td[2][text()='",
				EDITOFSTATUS 					= "/parent::tr/td[1]/a",
				STATUSTYPEVALUEPART1 			= "//td[2][text()='",
				STATUSTYPEVALUEPART2 			= "']/parent::tr/td[1]/a",
				PRIVATE_STATUS_TYPE_VISIBILITY	= "input[value='PRIVATE']",
				SELECT_STATUS_TYPE_PAGE			= "//div[@id='topSubNav']/h1[text()='Select Status Type']",
				STATUS_REASON_PART1  			= "//input[@value='",
		        STATUS_REASON_PART2  			= "[@name='statusReasonID']",
		        STATUS_REASON_FOR_STATUSES		= "[@name='status_reason_id']",
		        STATUS_TYPE_LIST_PAGE			= "//h1[text()='Status Type List']",
		        STATUS_REASON_REQUIRED          = "input[name='reasonRequired']",
		        STATUS_COLOR_PART1				="//td[text()='",
		        STATUS_COLOR_PART2				="/following-sibling::td/font[text()='",
		        DISPLAY_NEDOCS_LABELS			="//td[text()='Display NEDOCS labels:']/following-sibling::td/input[@name='nedocsTextDisplay'][1]",
		        RESOURCE_TYPE_VALUE				= "//input[@value='",
		        CANCEL_BUTTON                   ="input[class='emsButtonText'][value='Cancel']",
		        EDIT_LINK                       ="']/preceding-sibling::td/a[text()='edit']",
		        ROLES_WITH_UPDATE_RIGHT          ="input[value='roleUpdate']",
		        ROLES_WITH_VIEW_RIGHT            ="input[value='roleView']",
		        ROLE_UNDER_VIEW                  ="'][@name='roleView']",
		        ROLE_WITH_VIEW_RIGHT_PART2		= "[name='roleView']",
		 		ROLE_WITH_UPDATE_RIGHT_PART3	= "[name='roleUpdate']",
		 	    EDIT_FIRST_STATUS_TYPE			= "//div[@id='mainContainer']/table[@summary='Status Types']/tbody/tr[1]/td/a[text()='edit']",
		 	    ROLE_SECTION					= "input[value='",
		        STATUS_TYPE_TABLE				= "//table[@summary='Status Types']",
		        FOLLWOING_SIBLING_TEXT			= "/following-sibling::td[text()='",
		        STATUSES_TABLE					= "//table[@id='listStatuses']",
		        RE_ORDER_STATUSES				= "input[value='Re-order Statuses']",
		        DONE_RE_ORDERING				= "input[value='Done Re-ordering']",
		        WARNING_RE_ORDERING				= "//div[@id='saveWarning']/span[text()='Please note:']",
		        WARNING_SAVE_RE_ORDERING		= "//div[@id='saveWarning']/ul/li[text()=\"You must click on the 'Save' button below to save your status order changes.\"]",
		        WARNING_CANCEL_RE_ORDERING		= "//div[@id='saveWarning']/ul/li[text()=\"Click on the 'Cancel' button below to undo your status order changes.\"]",
		        STATUSES_PART1					= "']/following-sibling::td/font",
		        TEXT_PART						= "[text()='",
		        STATUSES_LINK_OF_MST			= "']/preceding-sibling::td/a[text()='statuses']",
		        ROLE_UNDER_UPDATE                ="'][@name='roleUpdate']";
	}
}