package EMR.Locators;

public class Views {

	public static class Locators {
		
		

		public static final String CLOSINGBRACKET 						= "']",
				CLOSINGTWOBRACES                  						= "')]",
				ANCHOR_TAG_WITH_TEXT 									= "//a[text()='",
				UPDATE_STATUS_UNDER_VIEW_RESOURCE_DETAIL				= "/parent::td/following-sibling::td[1]",
				RESOURCETYPE_AND_STATUSTYPE_PART1  						= "//a[text()='",
				RESOURCETYPE_AND_STATUSTYPE_PART2  						= "']/parent::th/following-sibling::th/a[text()='",
				RESOURCETYPE_AND_RESOURCE_PART2							= "']/ancestor::thead/following-sibling::tbody/tr/td[2]/a[text()='",
				VIEW_TABLE_PART1										= "//table[@id='rtt_",
				COMMENT_COLUMN											= "']/thead/tr/th[text()='Comment']",
				LAST_UPDATE_COLUMN										= "",
				BY_USER_COLUMN											= "",
				STATUSTYPE_COLUMN										= "",
				SETUP_CUSTOM_VIEW_LINK									= "Click here to setup your custom view",
				ADD_MORE_RESOURCES										= "input[value='Add More Resources']",
				FIND_RESOURCES_PAGE										= "//div[@id='topSubNav']/h1[text()='Find Resources']",
				SEARCH_IN_FIND_RESOURCES								= "searchName",
				SEARCH_BUTTON											= "input[value='Search']",
				RESOURCE_CHECKBOX_IN_FIND_RESOURCE_PART1				= "//table[@id='tbl_resourceID']/tbody/tr/td/input[@value='",
				ADD_TO_CUSTOM_VIEW										= "input[value='Add to Custom View']",
				OPTIONS_BUTTON											= "input[value='Options...']",
				EDIT_CUSTOM_VIEW_OPTIONS_PAGE							= "//div[@id='topSubNav']/h1[text()='Edit Custom View Options (Columns)']",
				DISPLAY_COMMENTS_CHECKBOX								= "showComments",
				DISPLAY_LAST_UPDATED_TIME								= "showUpdateTime",
				DISPLAY_LAST_UPDATED_USER								= "showUpdateUser",
				SHOW_SUMMARY											= "showTotals",
				STATUS_TYPES_CHECKBOX_IN_EDIT_CUSTUM_VIEW_OPTIONS_PART1	= "//input[@value='st_",
				SAVE_BUTTON												= "input[value='Save']",
				EDIT_CUSTOM_VIEW_PAGE									= "//div[@id='topSubNav']/h1[text()='Edit Custom View']",
				RESOURCE_TYPE_AND_RESOURCE_IN_CUSTOM_VIEW_TABLE_PART1	= "//table[@summary='Status for ",
				RESOURCE_TYPE_AND_RESOURCE_IN_CUSTOM_VIEW_TABLE_PART2	= "']/tbody/tr/td/a[text()='",
				OPTIONS_TABLE                               			= "//fieldset/legend/b[text()='Options']",
				NO_STATUSES_IN_CUSTOM_VIEW_HEADER           			= "//h1[text()='No Statuses in Custom View']",
				SET_UP_CUSTOM_VIEW_LINK2                    			= "Click here to add status columns to your custom view",
				STATUS_TYPES_UNDER_CUSTOM_VIEW              			= "']/thead/tr/th/a[text()='",
				RT_RESOURCE_AND_STATUSTYPE_PART1  						= "//th[text()='",
				RT_RESOURCE_AND_STATUSTYPE_PART2  						= "']/following-sibling::th/a[text()='",
				NO_RESOURCES_MATCH_TEXT                     			= "//h2[text()='No resources match your criteria...']",
		        SUMMERY_TOTALS_SECTION_PART                 			= "//td[@class='summary st_",
		        VIEW_SNAP_SHOT_DETAIL_PART1                 			= "//td[contains(text(),'",
		        VIEW_SNAP_SHOT_DETAIL_PART2                 			= "')]/following-sibling::td[contains(text(),'",
		        VIEW_SNAP_SHOT_HEADERS_PART1                			= "//th[contains(text(),'",
		        VIEW_SNAP_SHOT_HEADERS_PART2                			= "')]/following-sibling::th[contains(text(),'",
		        VIEW_NAME_IN_VIEW_SNAP_SHOT                 			= "//h2[contains(text(),'",
		        RESOURCE_NAME_UNDER_VIEW	                			= "//td[@class='resourceName']/a[text()='",
		        RESOURCE_NAME_IN_FIND_RESOURCE_PART1					= "//td[text()='",
		        RESOURCE_NAME_IN_FIND_RESOURCE_PART2					= "']/preceding-sibling::td[text()='",
		        FIND_RESOURCE											= "resourceFinder",
		        MAP_POPUP												= ".maxheight",
		        FIND_RESOURCE_PART1										= "//select[@id='resourceFinder']/option[text()='",
		        COLONSPACE												= ": ",
		        NORESOURCEVALIDATION									= "//h2[text()='No resources match your criteria...']",
		        THERE_ARE_NO_STATUSES_TO_DISPLAY_IN_YOUR_CUSTOM_VIEW 	= "//p[text()='There are no statuses (columns) to display in your custom view.']",
		        CUSTOMIZE 												= "customize",
		        TABLE_CELL_WITH_TEXT_PART1 								= "//div[text()='",
		        TABLE_CELL_WITH_TEXT_PART2 								= "']/ancestor::td/div[@id='itemBox']",
		        CANCEL 													= "input[value='Cancel']",
		        VERIFY_STATUS_TYPES										= "//form[@name='form1']/div/div/b[text()='",
		        CUSTOM_VIEW_MAP_PAGE                                    = "//div[@id='topSubNav']/h1[text()='Custom View - Map']",
		        STATUS_TYPE_COLOUR_PART1 								= "//td[@id='v_",
				STATUS_TYPE_COLOUR_PART2 								= "[@class='addToolTipText statusGreen editable']",
				TEXT                                                    ="[text()='",
				UPDATED_STATUS_TYPE_PART1								= "//tr[contains(@class,'rtr_",
				UNDERSCORE												= "_",
				UPDATED_STATUS_TYPE_PART2								= "')]/td[@id='v_",
				SUMMARY_OF_RESOURCETYPE									= "//table[@summary='Status for ",
				TABLE_ID_PART1											= "//table[@id='",
			    TABLE_ID_PART2											= "']//a[text()='",
			    TABLE_ID_PART3											= "']/parent::th/preceding-sibling::th",
			    STATUSTYPE_VALUE_PART1									= "']/tbody/tr//a[text()='",
			    STATUSTYPE_VALUE_PART2									= "']/parent::td/following-sibling::td[",
			    SQUARE_BRACKET											= "]",
			    CUSTOM_VIEW_TABLE_PAGE                                  = "//div[@id='topSubNav']/h1[text()='Custom View - Table']",
			    TABLE_HEADER_TEXT                                       ="//th/a[text()='",
		        STATUS_TYPES_IN_VIEW                                    = "']/following::th/a[text()='",
		        UPDATED_REASONS_UNDER_VIEW                              ="']/parent::td/following-sibling::td[2][text()='",
		        STATUS_CELL_OF_STATUS_TYPE_PART1                        ="td[onclick='return updateStatus(",
		        STATUS_CELL_OF_STATUS_TYPE_PART2                        =");']",
		        COMMENT_HEADER_PART2									= "']/thead/tr/th";
	}
}