package EMR.Locators;

public class View {
	public static class Locators {

		public static final String CLOSINGBRACKET = "']",
				CREATENEWVIEW 						= "input[value='Create New View']",
				VIEWNAME 							= "//tr[@title='View Name']//input",
				VIEW_DESCRIPTION 					= "//tr[@title='Description']//textarea",
				NEXT 								= "input[value='Next']",
				SAVE_OF_CREATE_NEW_VIEW 			= "//input[@value='Save']",
				REGION_NAME 						= "//a[@id='regionName']",
				RESOURCES 							= "//li/a[text()='Resources']",
				STATUS_TYPES 						= "//li/a[text()='Status Types']",
				EDIT_REGION_DEFUALT 				= "//td[text()='Region Default (default)']/preceding-sibling::td/a[text()='Edit']",
				REGIONS 							= "//li/a[text()='Regions']",
				CANCELOFCREATENEWVIEW 				= "//div[@class='align-right']/input[@value='Cancel']",
				CUSTOMIZERESOURCEDETAILVIEW 		= "input[value='Customize Resource Detail View']",
				ENTERSECTIONNAME 					= "input[value='Enter New Section Name']",
				CREATESECTION 						= "input[value='Create Section']",
				SAVE 								= "input[value='Save']",
				ADVANCED 							= "//li/a[text()='Advanced']",
				RESOURCETYPESTATUSESBYCOLUMNINPUT 	= "/ancestor::td/following-sibling::td[1]/input",
				NEWRTADDEDINFUTURESTATUSESBYCOLUMN	= "//span[text()='New Resource Types added in future']/ancestor::td/following-sibling::td[1]/input",
				RESOURCETYPECOMMENTSINPUT 			= "/ancestor::td/following-sibling::td[2]/input",
				NEWRTADDEDINFUTURECOMMENTS 			= "//span[text()='New Resource Types added in future']/ancestor::td/following-sibling::td[2]/input",
				NEWRTADDEDINFUTURE 					="//span[text()='New Resource Types added in future']/preceding-sibling::input",
				NEWRTADDEDINFUTUREUSER 				= "//span[text()='New Resource Types added in future']/ancestor::td/following-sibling::td[4]/input",
				NEWRTADDEDINFUTURERESOURCES 		= "//span[text()='New Resource Types added in future']/ancestor::td/following-sibling::td[5]/input",
				RESOURCETYPEFUTURERESOURCESINPUT 	= "/ancestor::td/following-sibling::td[5]/input",
				RESOURCETYPEUSERINPUT 				= "/ancestor::td/following-sibling::td[4]/input",
				RESOURCETYPETIMESTAMPINPUT 			= "/ancestor::td/following-sibling::td[3]/input",
				SELECTREGION 						= "//span[text()='",
				SELECTREGION1 						= "/preceding-sibling::input",
				SELECTRESOURCE						= "/parent::td/preceding-sibling::td[1]/input",
				SELECTSTATUSTYPES					= "//td//a[text()='",
				SELECTSTATUSTYPES1					= "/ancestor::td/preceding-sibling::td[1]/input",
				VERIFYVIEW							= "//table[@id='listViews']/tbody/tr/td[2][text()='",
				EDITVIEW							= "//td[text()='",
				EDITVIEW1							= "/preceding-sibling::td/a[text()='Edit']",
				LOADING								= "//div[@id='TB_load']/img",
				VIEW_LIST_PAGE 						= "//div[@id='topSubNav']/h1[text()='Region Views List']",
				LOADING_1							= "//div[@id='TB_load'][contains(@style,'none')]/img",
				VIEW_TABLE_PART1					= "//table[@id='rtt_",
				COMMENT_COLUMN						= "']/thead/tr/th[text()='Comment']",
				LAST_UPDATE_COLUMN					= "",
				BY_USER_COLUMN						= "",
				STATUSTYPE_COLUMN					= "']/tbody/tr/td/a[text()='";
	}
}