package EMR.Locators;

public class ViewUnderSetup {
	public static class Locators {

		public static final String CLOSINGBRACKET 				= "']",
				SPAN_WITH_TEXT									= "//span[text()='",
				CREATENEWVIEW 									= "input[value='Create New View']",
				VIEWNAME 										= "//tr[@title='View Name']//input",
				VIEW_DESCRIPTION 								= "//tr[@title='Description']//textarea",
				NEXT 											= "input[value='Next']",
				SAVE_OF_CREATE_NEW_VIEW 						= "//input[@value='Save']",
				REGION_NAME 									= "//a[@id='regionName']",
				RESOURCES 										= "//li/a[text()='Resources']",
				STATUS_TYPES 									= "//li/a[text()='Status Types']",
				EDIT_REGION_DEFUALT 							= "//td[text()='Region Default (default)']/preceding-sibling::td/a[text()='Edit']",
				REGIONS 										= "//li/a[text()='Regions']",
				CANCELOFCREATENEWVIEW 							= "//div[@class='align-right']/input[@value='Cancel']",
				CUSTOMIZE_RESOURCE_DETAIL_VIEW 					= "input[value='Customize Resource Detail View']",
				ENTERSECTIONNAME 								= "input[value='Enter New Section Name']",
				CREATESECTION 									= "input[value='Create Section']",
				SAVE 											= "input[value='Save']",
				ADVANCED 										= "//li/a[text()='Advanced']",
				RESOURCE_TYPE_STATUSES_BY_COLUMN_INPUT 			= "/ancestor::td/following-sibling::td[1]/input",
				NEW_RT_ADDED_IN_FUTURE_STATUSES_BY_COLUMN		= "//span[text()='New Resource Types added in future']/ancestor::td/following-sibling::td[1]/input",
				RESOURCE_TYPE_COMMENTS_INPUT 					= "/ancestor::td/following-sibling::td[2]/input",
				NEW_RT_ADDED_IN_FUTURE_COMMENTS 				= "//span[text()='New Resource Types added in future']/ancestor::td/following-sibling::td[2]/input",
				NEW_RT_ADDED_IN_FUTURE 							= "//span[text()='New Resource Types added in future']/preceding-sibling::input",
				NEW_RT_ADDED_IN_FUTURE_USER 					= "//span[text()='New Resource Types added in future']/ancestor::td/following-sibling::td[4]/input",
				NEW_RT_ADDED_IN_FUTURE_RESOURCES 				= "//span[text()='New Resource Types added in future']/ancestor::td/following-sibling::td[5]/input",
				RESOURCE_TYPE_FUTURE_RESOURCES_INPUT 			= "/ancestor::td/following-sibling::td[5]/input",
				RESOURCE_TYPE_USER_INPUT 						= "/ancestor::td/following-sibling::td[4]/input",
				RESOURCE_TYPE_TIME_STAMP_INPUT 					= "/ancestor::td/following-sibling::td[3]/input",
				SELECT_REGION 									= "//span[text()='",
				SELECT_REGION1 									= "/preceding-sibling::input",
				SELECT_RESOURCE									= "/parent::td/preceding-sibling::td[1]/input",
				SELECT_STATUS_TYPES								= "//a[text()='",
				SELECT_STATUS_TYPES1							= "/ancestor::td/preceding-sibling::td[1]/input",
				VERIFY_VIEW										= "//table[@id='listViews']/tbody/tr/td[2][text()='",
				EDITVIEW										= "//td[text()='",
				EDITVIEW1										= "/preceding-sibling::td/a[text()='Edit']",
				LOADING											= "//div[@id='TB_load']/img",
				VIEW_LIST_PAGE 									= "//div[@id='topSubNav']/h1[text()='Region Views List']",
				LOADING_1										= "//div[@id='TB_load'][contains(@style,'none')]/img",
				SPAN_TEXT										= "//td/span[text()='",
				PROCEED_WITHOUT_SAVING                      	= "input[value='Proceed Without Saving']",
				COPY                                        	= "/preceding-sibling::td/a[text()='Copy']",
				SELECT_RESOURCE_TAB_TEXT                    	= "//span[text()='Select status types to be included in this view.']",
				SELECT_STATUSTYPE_TAB_TEXT                  	= "//span[text()='Select status types to be included in this view.']",
				USERS_TAB										= "//li/a[text()='Users']",
				VISIBILITY_FOR_USERS							= "//span[text()='Visible to all users']/preceding-sibling::input",
				USER_ACCESS_TO_VIEW_PART2						= "']/parent::td/preceding-sibling::td/input",
				ST_NAME_IN_EDIT_RESOURCE_DETAIL_VIEW_SECTIONS	= "//div[@id='itemBox']/ul/li/div[text()='",
				EDIT_SECTION_PART_2							 	= "/following-sibling::div/div[@id='editGroupLinks']/a[text()='Edit']",
				DELETE_REGION_VIEW_PART1						= "//table[@id='listViews']//td[text()='",
				DELETE_REGION_VIEW_PART2						= "']/preceding-sibling::td/a[text()='Delete']",
				DELETE_VIEW_CONFIRMATION_PAGE					= "//div[@id='topSubNav']/h1[text()='Delete View Confirmation']",
				DELETE_IN_CONFIRMATION_SCREEN					= "input[value='Delete']",
				COPY_OF_VIEW_PART2								= "']/preceding-sibling::td/a[text()='Copy']",
				COPY_VIEW_HEADER_PART1							= "//div[@id='topSubNav']/h1[text()='Create View: Copy of ",
		        CREATED_SECTION                                 = "input[value='",
		        SECTION_LINKS                                   = "div[id='groupEditControls']";       
	}
}