package lib.dataObject;

public class User_data {

	public String strNewUserName = "auto"+System.currentTimeMillis(),
			      strSysAdm = "Admin"+System.currentTimeMillis(),  
                  strNewPassword = "Qsg@2015",
                  strFullName = "FN"+strNewUserName,
                  strSecNewUserName = "AutoSec"+System.currentTimeMillis(),
                  strPrimaryMailId = "autoemres@outlook.com",
                  strPrimaryPwsd = "Qsg@2006",
                  strRole = "(Any Role)",
                  strResourceType = "(Any Resource Type)",
                  strEquals = "Username",
                  strUsername = "Username",
                  strsearchOption = "Equals",
                  MailURL = "https://emresource.qa.intermedix.com",
                  strFirstName = "FN"+System.currentTimeMillis(),
                  strMiddleName = "MN"+System.currentTimeMillis(),
                  strLastName="LN"+System.currentTimeMillis(),
                  strOrganization = "QSG",
                  strEmail = "autoemres_1@outlook.com",//"autoemr@qsgsoft.com",
                  strPhone = "5555551234",
                  strEditedFullName = "EdFN"+strNewUserName,
                  strEditedFirstName = "EFN"+System.currentTimeMillis(),
                  strEditedMiddleName = "EMN"+System.currentTimeMillis(),
                  strEditedLastName="ELN"+System.currentTimeMillis(),
                  strEditedOrganization = "QSG1",
                  strEditedPhone = "5555551234",
                  strNewUserName1 = "Auto1"+System.currentTimeMillis(),
                  strNewUserName2 = "Auto2"+System.currentTimeMillis(),
                  strFullName1 = "FN1"+strNewUserName1,
                  strFullName2 = "FN2"+strNewUserName2,
        		  strNewUserName3 = "Auto3"+System.currentTimeMillis(),
                  strNewUserName4 = "Auto4"+System.currentTimeMillis(),
                  strNewUserName5 = "Auto5"+System.currentTimeMillis(),
                  strFullName3 = "FN3"+strNewUserName3,
                  strFullName4 = "FN4"+strNewUserName4,
                  strNewPassword1 = "Abcd@1234",
                  strEditedFullName1 = "EdFN",
                  strEditedOrganization1 = "QSG2",
                  strEditedPhone1 = "5555551234",
                  strNoRole="(No Role)",
                  strUserPwd = "Abcd@1234",
                  strContains = "Contains",
                  strInvalidPrimaryMailId ="autoemres#outlook.com",//autoemr#qsgsoft.com",
                  strEmailAddress = "Email Address",
                  strSetupResourceTypesValue = "2",
                  strConfigureRegionalUserAccessValue = "5",
                  strMaintainEventsValue = "13",
                  strUserMayConfigureFormSecurityValue = "33",
                  strFormUserMayCreateAndModifyValue = "39",
        		  strStartsWith = "Starts With",
                  strEndsWith = "Ends With",
                  strNotEqualTo = "Not Equal To",
                  strHavBedRight = "HAvBED - Schedule and Activate HAvBED Interface",
                  strSetUpUsersAccountsRight = "User - Setup User Accounts",
                  strEmail1 = "autoemres_2@outlook.com";
                 
}