package EMR.Locators;

public class OtherRegionList {

	public static class Locators {
		
		public static final String CLOSINGBRACKETS 			= "']",
				TABLECELLWITHTEXT 							= "//td[text()='",
				CREATNEWRELATION 							= "input[value='Create New Relationship']",
		        OTHERREGHEADER								= "//h1[text()='Other Region List']",
		        OTHERREGIONVIEWPART1 						= "//div[2]/table[1]/tbody/tr/td[text()='",
		        DELETELINK 									= "']/preceding-sibling::td/a[@title='delete']",
		        VERIFYLINK 									= "']/preceding-sibling::td/a[@title='verify']",
		        UNVERIFYLINK 								= "']/preceding-sibling::td/a[@title='unverify']",
		        DEACTIVATELINK 								= "']/preceding-sibling::td/a[@title='deactivate']",
		        ACTIVATELINK 								= "']/preceding-sibling::td/a[@title='activate']",
		        REGIONVERIFIED 								= "']/following::td[text()='Yes'][1]",
		        REGIONACTIVATED 							= "']/following::td[text()='Yes'][2]",
		        VERIFYACTIVATEDRELATIONSHIP					= ".centerSuccessBox>p",
		        MANAGE_USERS_LINK							= "/preceding-sibling::td/a[text()='manage users']",
		        ASSIGNE_FOR_ALL_USERS 						= "assignForAllUsers",
		        ASSIGNE_FOR_ALL_USERS_UNSELECTED 			= "input[id='assignForAllUsers'][value='N']",
		        ASSIGNE_FOR_ALL_USERS_SELECTED 				= "input[id='assignForAllUsers'][value='Y']",
		        SAVE										= "input[value='Save']",    
		        ASSIGNE_USERS_TO_PAGE_PART1					= "//h1[text()='Assign Users to view ",
		        REGIONTEXT									= " region']",
		        REGIONS_THAT_CAN_VIEW_SECTION				= "//h1[text()='Regions that can view ",
		        PAGE_HEADER									= "//h1[text()='",
		        REGION_CAN_VIEW_SECTION						= " can view']",
		        TABLE_HEADERS_OF_REGIONS_CAN_VIEW_SECTION	= "//table[@summary='Regions that can view this region']/thead/tr/th[text()='",
		        TABLE_HEADER_OF_CAN_VIEW_SECTION			= "//table[@summary='This region can view']/thead/tr/th[text()='",
		        NAME_COLUMN_OF_REGIONS_CAN_VIEW_SECTION		= "//table[@summary='Regions that can view this region']/thead/tr/th/a[text()='Name']",	
		        ACTIVATE_STATUS								= "/following::td[2][text()='",
		        VERIFIED_STATUS								= "/following::td[1][text()='",
		        VERIFIED_BY									= "/following::td[3][text()='",
		        VERIFIED_ON									= "/following::td[4][text()='",
		        ACTIVATED_BY								= "/following::td[5][text()='",
		        ACTIVATED_ON								= "/following::td[6][text()='",
		        REGION_UNDER_CAN_VIEW_SECTION				= "//table[@summary='This region can view']/tbody/tr/td[text()='",
		        OTHERG_REAGION_TAB 							= "Other Regions",
		        AGRREMENT_SUCCESS_MESSAGE_PART1				= "//div[@class='centerSuccessBox']/p[text()='Mutual aid relationship with ",
		        REGION_UNDER_THAT_CAN_VIEW_SECTION			= "//table[@summary='Regions that can view this region']/tbody/tr/td[text()='",
		        SELECTPARTICULARUSERPART2 					= "']/preceding-sibling::td/input",
		        MUTUALAIDEDREGIONPART1 						= "//div[@id='topSubNav']/h1[text()='",
		        PARTICULARVIEWPART1 						= "//td/a[text()='",
		        SHAREDSTATUSTYPEBUTTON 						= "//input[@value='Share Status Types']",
		        SELECTSTATUSTYPEPART1 						= "input[value='",
		        EDIT_OTHERREGION_SECURITY_RESOURCES			= "//h1[text()='Edit Other Region Security - Resources']",
		        SHARERESOURCES 								= "input[value='Share Resources']",
		        BACK 										= "input[value='Back']",
				RESOURCECHECKBOX							= "input[value='",
				USER_RESOURCECHECKBOX 						= "[disabled='disabled'][checked='checked']",
				VIEW_OTHER_REGION_SECURITY_RESOURCES		= "//h1[text()='View Other Region Security - Resources']";
	}            
}
