package dataObject;

public class MedwebRadiologyStatistics_data {
	public String strTimePeriod = "Today",
			      strThisYear = "This Year",
			      strAllDays = "All Days",
			      strStudy = "Remap",
			      strModality = "DS",
			      strStatusBoth = "Both",
			      strStatusRead = "Read",
				  strStatusUnRead = "Unread",
			      strLimit50 = "50",
			      strStartDate = "Start Date:",
			      strEndDate = "End Date:",
			      strAdminGroup = "Administrator (admin)",
			      strEventAssign = "assign",
			      strEventCreate = "create",
			      strEventCreatePatient = "create_patient",
			   	  strEventDeletePatient = "create_patient",
		 		  strEventDelete = "delete",
	    		  strEventDeleteReport = "delete_report",
			      strEventEdit = "edit",
				  strEventEditPatient = "edit_patient",
			      strEventMailHtml = "mail_html",
			      strEventMailMww = "mail_mww",
			      strEventMailPdf = "mail_pdf",
			      strEventMerge = "merge",
			      strEventMove = "move",
			      strEventNewReport = "new_report",
			      strEventOrder = "order",
			      strnewAddendum = "new_addendum",
			      strEventQcReleased = "qc_released",
			      strEventRead = "read",
			      strEventReceiveReport = "receive_report",
			      strEventReceiveReportSigned = "receive_report_signed",
			      strEventSend = "send",
			      strEventSendReport = "send_report",
			      strEventSignReport = "sign_report",
			      strEventStat = "stat",
			      strEventUnRead = "unread",
			      strEventView = "view",
			      strEventViewReport = "view_report",
			      strEventViewZip = "view-zip";

}
