package EMR.Locators;

public class Resources {
	public static class Locators {
		public static final String CLOSEBRACKETS 		= "']",
				CLOSINGTWOBRACES 			            = "')]",
				TABLECELLWITHTEXT 						= "//td[text()='",
				CREATENEWRESOURCE 						= "//input[@value='Create New Resource'][@type='button']",
				RESOURCENAME 							= "resourceName",
				RESOURCEFIRSTNAME 						= "firstName",
				RESOURCELASTNAME 						= "lastName",
				STANDARDRESOURCETYPELIST 				= "standardResourceTypeID",
				RESOURCETYPELIST 						= "//select[@name='resourceTypeID']",
				DESCRIPTION 							= "abbreviation",
				SAVE 									= "input[value='Save'][type='submit']",
				CREATENEWSUBRESOURCE 					= "//input[@value='Create New Sub-Resource'][@type='button']",
				STREETADDRESS 							= "streetAddress",
				CITYNAME 								= "city",
				STATENAME 								= "stateAbbrev",
				ZIPCODE 								= "zipCode",
				COUNTY 									= "county",
				LOOKUPADDRESS 							= "input[value='Lookup Address']",
				MAP 									= "map",
				SHAREWITHOTHERREGION 					= "input[name='shareWithOtherRegions']",
				VIEWRESOURCE 							= "input[value='viewRight']",
				SUBRESOURCELINKPART1 					= "//table/tbody/tr/td[5][text()='",
				SUBRESOURCELINKPART2 					= "']/preceding-sibling::td[4]/a[contains(text(),'Sub-Resources')]",
				RESOURCEVALUE							= "//div[@id='mainContainer']/table[2]/tbody/tr/td[5][text()='",
				RESOURCEVALUE1							= "/parent::tr/td[1]/a",
				VIEW_RESOURCE_UNDER_CREATE_RESOURCE		= "//td[text()='View Rights:']/following-sibling::td/input[@name='viewRightForAllUsersInd'][@value='Y']",
				ADD_STATUS_TYPE							= "']/preceding-sibling::td/a[text()='Edit']",
				STATUSTYPE 								= "//input[@name='statusTypeID'][@value='",
				STATUS_TYPES_LINK                   	= "']/preceding-sibling::td/a[text()='Status Types']",
				EDIT_RESOURCE_LEVEL_STATUS_TYPES    	= "//h1[text()='Edit Resource-Level Status Types']",
				STATUS_TYPES_UNDER_EDIT_RESOURCE_LEVEL	= "//td/input[@value='",
				SUBRESOURCELISTPAGE						= "//h1[contains(text(),'Sub-Resource List for ",
				CLOSEBRACKETSWITHPARENTHESIS 			= "')]",
				SUBRESOURCEVALUE						= "//div[@id='mainContainer']/table[2]/tbody/tr/td[text()='",
				TABLE_ROW_FOLLOWED_BY_TABLE_DATA    	= "//tr/td[text()='",
				USERS_LINK                          	= "']/preceding-sibling::td/a[text()='Users']",
				STATUS_TYPE_VALUE						= "input[value='",
				CANCEL     								= "input[value='Cancel']",
				SELECTED_RESOURCETYPE					= "//option[@selected='selected'][text()='",
				VIEW_RESOURCE_RIGHT_ON_USER_PART1       = "input[value='",
				VIEW_RESOURCE_RIGHT_ON_USER_PART2		= "'][name='viewRight']",
				STATUS_TYPES_AT_RESOURCE_LAVEL          = "//td/a[contains(text(),'",
				ASSIGN_USERS_TO_RESOURCE_PAGE           = "//h1[text()='Assign Users to ",
				USERLINK_CORRESPONDING_TO_FIRST_RESOURCE ="//div[@id='mainContainer']/table/tbody/tr[1]/td[1]/a[text()='Users']",
				ASSOCIATED_WITH_RIGHT_ON_USER_PART1     = "input[value='",
				ASSOCIATED_WITH_RIGHT_ON_USER_PART2		= "'][name='association']",
				RUNREPORT_RIGHT_ON_USER_PART1      		= "input[value='",
				RUNREPORT_RIGHT_ON_USER_PART2			= "'][name='reportRight']",
				UPDATE_RIGHT_ON_USER_PART1      		= "input[value='",
				UPDATE_RIGHT_ON_USER_PART2				= "'][name='updateRight']",
				EMR_ERROR_TITLE							= "//span[@class='emsErrorTitle'][text()='The following error occurred on this page:']",
				EMR_ERROR								= "//div[@class='emsError']/ul/li[text()='A user that has any of Associated With, Update Status, or Run Reports for a resource must have View Resource.']",
				EDIT_RESOURCE_PAGE						= "//h1[text()='Edit Resource']",
				ABBREVIATION_AND_RT						= "']/following-sibling::td[text()='";
	}
}