package lib.dataObject;

public class EventSetUp_data {
	
	public String strEventTemplate = "ET" + System.currentTimeMillis(),
			strTemplateDefinition = "ET from Automation",
			strEventTemplate1 = "ET1" + System.currentTimeMillis(),
			strEventTemplate2 = "ET2" + System.currentTimeMillis(),
			strAdHocEventTemplate = "Ad Hoc Event",
			strCity = "Los Angeles",
			strState = "California",
			strCountry = "Fresno County",
			strZipCode = "1234",
			strNone = "- None -",
			strNotParticipationg  = "-- Not Participating --",
			stMultiStatus = "Yes",
			strEventStatus = "Ongoing",
			strCountrycode = "CA",
			strEDITEventTemplate = "EDIT" + System.currentTimeMillis(),
			strEDITemplateDefn = "ET from testing",
			strEventTempIcon="/icon/event43.png",
			strEventTempActive="Active",
			strETBlueColor = "Blue",
			strETYelloColor="Yellow",
			strETPurpuleColor="Purple",
			strETAmbulance ="Ambulance",
			strAmbulanceIcon = "/icon/event7.png",
			strEventTempDisabled="Disabled",
			strAmberAlert = "Amber Alert / Missing Child",
			strBlackColor = "Black",
			strEventTemplate3 = "ET3" + System.currentTimeMillis(),
			strStdEventType="Fire",
			strDefaultEventName = "DefEveName" + System.currentTimeMillis(),
			strDefaultEventDefinition = "DefEveDefinition" + System.currentTimeMillis(),
			strEditDefaultEventName = "EdDefName" + System.currentTimeMillis(),
			strEditDefaultEventDefinition = "EdDefDefinition" + System.currentTimeMillis(),
			strEditCity = "Adams",
			strEditState = "Wisconsin",
			strEditCounty = "Adams County",
			strEditZipCode = "93510",
			strEditCountrycode = "WI";
}
