package lib.dataObject;

public class EMTrack_data {
	
	public String strUserName = "ColoradoRegAdmin",			 	  
		      strPassword = "Abc@1234",
		      strRegionName = "Z_BQS_Build_8689",
		      strPatientID = "AutoPatientID" + System.currentTimeMillis(),
		      strPatientID1 = "AutoPatientID1" + System.currentTimeMillis(),
		      strMaleGender = "Male",
		      location = "Memorial Hospital North",
		      provider = "Blackhawk1",
		      strUnit = "1234",
		      strETA3 = "5",
		      location1 = "Alta Vista Regional Hospital",
		      location2 = "Advanced Care Hospital of Southern NM",
		      strNewMexicolocation3 = "Alta Vista Regional Hospital",
		      provider1 = "Air Care",
		      strProvider2 = "Air Care",
		      strQsgTester = "qsgtester",
		      strQsgTesterPwd ="Abc@1234",
		      strMale = "Male",
		      strRegion = "New Mexico",
		      strNewMexicoReg = "New Mexico",
		      strPatientAgeData = "unknown",
		      strComplaintData = "unknown",
		      strTriageData = "N/A",
		      strPatientAge = "25",
		      strSetracRegion = "SETRAC Region",
    		  setracLocation = "Bayshore Medical",
    		  setracLocation1 = "M. D. Anderson",
    		  setracLocation2 = "Cornerstone of Houston - Clearlake",
    		  setracIncident = "**Excercise**  Hobby Airport Alert III MCI",
    		  setracIncident1="Default Incident",
		      setracProvider = "AutoMobileProviderForSetracWithUnits",
		      setracProvider1="Disaster EMS Unit",
		      setracProviderUnit = "AutoUnit",
		      strNewMexicoRegion = "New Mexico",
		      strNewMexicoLoc = "Fort Bayard Medical Center",
		      strNewMexicoProvider = "A Lovelace Clinic",
		      strNewMexicoLocation1 = "Nor-Lea General Hospital",
		      strNewMexicoLocation2 = "UNM Mental Health",
		      strColoradoRegion = "Colorado",
		      testInc="Test incident",
//		    setracIncident = "AutoIncident1436165251979",
		      setracLocation3 = "Cypress Creek Hospital",
		    setracLocation4 ="North Cypress Medical Center",
		    strImmeditteTraige="Immediate",
		    busProvider="Bus";
}