package lib.dataObject;

public class InterfaceInSetUp_data {

	public String strInterfaceType1 = "Chicago Get Hospital Status",
				  strInterfaceType2 = "Get Active Events",
				  strInterfaceType3 = "Get CAD Status",
				  strInterfaceType4 = "Get EDXL-HAVE 1.0",
				  strInterfaceType5 = "Get HAvBED 2.5.2 Information",
				  strInterfaceType6 = "Get Hospital Status",
				  strInterfaceType7 = "Get Region Configuration",
				  strInterfaceType8 = "Legacy Get Hospital Status",
				  strInterfaceType9 = "Post HAvBED 2.5.2 Information",
				  strInterfaceType10 = "Post Resource Detail Status",
				  strInterfaceType11 = "Update CAD Status",
				  strInterfaceType12 = "Update Resource Availability",
				  strInterfaceType13 = "Post Incoming Patient",
				  strInterfaceName = "Interface"+System.currentTimeMillis(),
				  strExistingPostIPNInterfaceName="postIPN",
				  strstrExistingPostIPNInterfacInColorado="PN interface",
				  strEditInterfaceName="Edit"+strInterfaceName,
				  strInterfaceDesc = "InterfaceDesc"+System.currentTimeMillis(),
				  strEditInterfaceDesc="Edit"+strInterfaceDesc,
				  strgetHospitalStatus="getHospitalStatus",
				  strpostResourceStatus="postResourceStatus",
				  strgetActiveEvents="getActiveEvents",
				  strPostResourceDetailStatus="postResourceDetailStatus",
				  strContInfo = "5555551234",
				  strEditContInfo="5555551234",
				  strInterfaceActiveStatus = "Active",
				  strInterfaceDisabledStatus = "Disabled",
				  defaultText = "getEdxlHave",
				  defaultText1 = "getCadStatus",
				  defaultText2 = "postCadStatus",
				  strInterfaceName1 = "EditInterface"+System.currentTimeMillis(),
				  strInterfaceDesc1 = "EditInterfaceDesc"+System.currentTimeMillis(),
				  strContInfo1 = "5555551234",
				  strNewMexcoResource1="Holy Cross Hospital",
				  strNewMexicoResource2="BigMo Santa Fe",
				  strNewMexicoResource3="Casa Real",
				  strSchemaForGetActiveEvents="EM Common Alert Protocol (wraps CAP 1.1) 1.1",
				  strParaMeterName="PARAMETRE"+System.currentTimeMillis(),
				  strParameterValue="Value"+System.currentTimeMillis(),
				  strSetracResources="Bayshore Medical",
				  strSertaceResoueces1="Doctors-Tidwell",
				  strColoradoResources="VA -Eastern Colorado",
				  strgetRegionalConfiguration="getRegionalConfiguration",
				  strParaMeterName1="PARAM1"+System.currentTimeMillis(),
				  strParameterValue1="Value1"+System.currentTimeMillis(),
				  strSchemaForregionalConfiguration="RegionConfiguration 1.0",
				  strLinkName1="edit",
				  strLinkName2="users",
				  strLinkName3="parameters",
				  strLinkName4="delete",
				  strSchemaForLegacyHospitalStatus="HospitalStatus draft/pre 1.0",
				  strgetChicagoStatus="getChicagoStatus",
				  strSchemaForgetChicagoStatus="IDPH_HAvBED 1.0",
				  strSetracResources2 ="Harris County Psychiatric Center",
					strSetracResources3 ="North Cypress Medical Center";

}
