package lib.dataObject;

import qaframework.lib.UserDefinedFunctions.Date_Time_settings;

public class Resource_data {

	Date_Time_settings objDate_Time_settings = new Date_Time_settings();
	String strTimeText = objDate_Time_settings.getCurrentDate("MM/dd/yyyy-hhmmss");
	String strAbbrevation = objDate_Time_settings.getCurrentDate("hhmm");
	
	public String strResourceFirstName = "FN",
			strResourceLastName = "LN",
			strResourceAbbrivation = "Abb",
			strResourceAbbrivation1 = "Acc",
			strResourceName = "RS"+ strTimeText,
	        strStandardResourceTypename="Hospital",
	        strResourceName1 = "RS1"+ strTimeText,
	        strResourceName2 = "RS2"+ strTimeText,
	        strResourceName3 = "RS3"+ strTimeText,
	        strResourceName4 = "RS4"+ strTimeText,
	        strResourceName5 = "RS5"+ strTimeText,
	        strResourceName6 = "RS6"+ strTimeText,					  
	        strStreetAddress = "StreetAddress",
	        strCity = "City",
	        strState = "California",
	        strZipcode = "12345",
	        strCounty = "Alpine County",
	        strSubResourceName = "SRS"+ strTimeText,
	        strSubResourceName1 = "SRS1"+ strTimeText,
	        strSubResourceName2 = "SRS2"+ strTimeText,
	        strSubResourceName3 = "SRS3"+ strTimeText,
	        strSubResourceName4 = "SRS4"+ strTimeText,
	        strColoradoResource="Memorial Hospital North^",
	        strColoradoResource1 = "Mercy Regional MC Centura III",
	        strColoradoResource2 = "Lutheran Medical Center^  III",
	        strStatusTypesOfLutheran = "ED Status",
	        strStandardResTypeId = "102",
	        strStandardResourceTypename1 = "Ambulance",
//	        strNewMexicoResource = "Fort Bayard Medical Center",
	        strNewMexicoResource = "Advanced Care Hospital of Southern NM",
	        strNewMexicoResource1 = "Alta Vista Regional Hospital",
	        strCaliforniaCode = "CA",
	        strEditedResName = "Edt"+strResourceName,
	        strEditedResAbb = "E"+strResourceAbbrivation,
	        strEditedResName2 = "Edt"+strResourceName1,
	    	strEditedResAbb2 = "E"+strResourceAbbrivation1,
	        strSetracResourceName = "Bayshore Medical",
	        strSetracResourceName1 = "M. D. Anderson",
	     	strSetracResourceName2 = "Cornerstone of Houston - Clearlake*",
	     	strSetracResourceName3 = "Columbus Community*",
	    	strSetracResourceName4 = "Icon Hospital*",
	    	strSetracResourceName5 = "Bellville St. Joseph Health Center*",
	        strNewMexicoResourceName = "Fort Bayard Medical Center",
	        strNewMexicoResourceName1 = "Nor-Lea General Hospital D Level 4",
	        strNewMexicoResourceName2 = "UNM Mental Health",
	        strResourceAbbrivation2 = "xyz",
	        strSpringfieldResource = "Fort Bayard Medical Center",
	        strEditedResFirstName = "Edt" + strResourceFirstName,
	        strEditedResLastName = "Edt" + strResourceLastName,
	        strHospital="Hospital",
	        strTraumaHospital="Trauma Hospital",
	        strTraumaLevel1="Trauma Level I",
	        strTraumaLevel2="Trauma Level II",
	        strTraumaLevel3="Trauma Level III",
	        strTraumaLevel4="Trauma Level IV",
	        strSubResourceIcon="/icon/map/hosp.png",
	        strSubResourceIcon1="/icon/map/ambu.png",
	        strEditedResName1 = "Edt"+strResourceName1,
	        strStandardResourceTypename2="Trailer",
	        strEditedResourceFirstName = "EDFN",
			strEditedResourceLastName = "EDLN",
	        strEditedStreetAddress = "StreetAddressOne",
	        strEditedCity = "CityOne",
	        strEditedState = "Louisiana",
	        strEditedZipcode = "23452",
	        strEditedCounty = "Acadia Parish",
	        strLouisianaCode = "LA",
	        strStandardRTHomeHealth = "Home Health",
	        strResourceAbbrivation3 = ""+strAbbrevation;
	
	public String[] strHeaders = {"Action", "Icon", "Active", "HAvBED", "AHA ID", "Name", "Abbreviation", "Resource Type"};
}