package EMR.Locators;

public class Shared {

	public static class Locators {
		public static final String CLOSING_BRACKETS 				= "']",
				APPSWITCHER											= "//div[@id='HEADER-selectApplication']/span[text()='EMResource']",
				USERSTEXT 											= "//div[@id='mainContainer']/table/tbody/tr/td/a[text()='Users']",
				SETUPLINK 											= "Setup",
				EVENTLINK 											= "//a[text()='Event']",
				EVENTMANAGEMENT 									= "//td/a[text()='Event Management']",
				STATUSTYPES 										= "//td/a[text()='Status Types']",
				RESOURCETYPES 										= "//td/a[text()='Resource Types']",
				RESOURCES 											= "//td/a[text()='Resources']",
				EVENTSETUP 											= "//td/a[text()='Event Setup']",
				VIEWS 												= "//td/a[text()='Views']",
				VIEW 												= "//div/a[text()='View']",
				REGIONDEFAULT 										= "//td/a[text()='Region Default (my default)']",
				REGIONS												= "Regions",
				ROLES 												= "Roles",
				OTHERREGION											= "//td/a[text()='Other Regions']",
				FORM  												= "Form",
				CONFIGUREFORMS										= "Configure Forms",
				ACTIVATEFORMS 										= "Activate Form",
				USERLINKS 											= "//td/a[text()='User Links']",
				MAP 												= "//td/a[text()='Map']",
				APPLICATIONTIME 									= "//table[@class='footer']/tbody/tr/td[3]/span[@id='statusTime']",
				INCOMINGPATIENT										= "Incoming Patients",
				PREFERENCES_LINK									= "//a[text()='Preferences']",
				USER_INFO											= "//td/a[text()='User Info']",
				PARTICULAR_VIEW_PART1								= "//td/a[text()='",
				HOME												= "//div/a/img[@src='/image/home.gif']",
				OTHER_REGIONS_LINK									= "//div[@class='mainNavigation subNav']/a[text()='Other Regions']",
				SETUPMENU_PAGE										= "//div[@id='topSubNav']/h1[text()='Setup Menu']",
				VIEWS_UNDER_SETUP									= "//td[text()='Administer regional views.']/preceding-sibling::td/a[text()='Views']",
				EVENTMENU_PAGE										= "//div[@id='topSubNav']/h1[text()='Event Menu']",
				USERSLIST_PAGE										= "//div[@id='topSubNav']/h1[text()='Users List']",
				EVENTMANAGEMENT_PAGE								= "//div[@id='topSubNav']/h1[text()='Event Management']",
				INTERFACES											= "//div[@id='mainContainer']/table/tbody/tr/td/a[text()='Interfaces']",
				INTERFACELIST_PAGE									= "//div[@id='topSubNav']/h1[text()='Interface List']",
				CUSTOM_VIEW											= "//td/a[text()='Custom']",
				CUSTOM_VIEW_TABLE_PAGE								= "//div[@id='topSubNav']/h1[text()='Custom View - Table']",
				FRAME 												= "Data",
				FRAME_DATA											= "//frame[@name='Data']",
				SEND_INCOMING_PATIENT_NOTIFICATION 					= "Send Incoming Patient Notification",
				REPORT												= "Report",
				RESOURCE_REPORTS									= "Resource Reports",
				INCOMING_PATIENT_NOTIFICATION_DETAILS				= "Incoming Patient Notification Details",
				INCOMING_PATIENT_NOTIFICATIONS     	  				= "Incoming Patient Notifications",
				CUSTOMIZE_LINK_AT_TOP   							= "#link_customize>a",
				USER_LINKS_LIST_PAGE								= "//div[@id='topSubNav']/h1[text()='User Link List']",
				SEARCH_LINK_IN_TOOL_BAR								= "//ul[@id='subNavList']/li/a[text()='Search']",
				REGION_VIEWS_LIST_PAGE								= "//h1[text()='Region Views List']",
				APPLICATION_TIME_FROM_FOOTER						= "//td/span[@id='statusTime']",
				PREFERENCES_MENU_PAGE								= "//div[@id='topSubNav']/h1[text()='Preferences Menu']",
				CUSTOMIZED_VIEW										= "//td/a[text()='Customized View']",
				FORM_MENU_PAGE										= "//div[@id='topSubNav']/h1[text()='Form Menu']",
				FORM_CONFIGURATION_PAGE								= "//div[@id='topSubNav']/h1[text()='Form Configuration']",
				SEND_INCOMING_PATIENT_NOTIFICATION_BUTTON 			= "input[value='Send Incoming Patient Notification']",
				SHOW_MAP                                    		= "//div[@id='link_show map']/a",
				STATUS_REASON                               		= "Status Reasons",
				PRINT_LINK                                  		= "//div[@id='link_print']",
				SPECIFIC_DATE_TIME_UNDER_PRINT_OPTION       		= "//input[@id='snapshotDateSelectRadio_selected']",
				SNAPSHOT_DATE                               		= "//input[@id='snapshotDate']",
				SNAPSHOT_HOUR                               		= "//select[@id='snapshotHours']",
				SNAPSHOT_MINUTE                             		= "//select[@id='snapshotMinutes']",
				GENERATTE_REPORT                            		= "//input[@id='submitSnapshot']",
				STATUS_CHANGE_PREFS									= "//td/a[text()='Status Change Prefs']",
				HEADER_PART											= "//div[@id='topSubNav']/h1[text()='",
				VIEW_MENU											= "//div[@id='topSubNav']/h1[text()='View Menu']",
				EDIT_VIEW_SCREEN_WITHOUT_VIEW_NAME					= "//div[@id='topSubNav']/h1[contains(text(),'Edit View:')]",
				SUB_MENU_UNDER_MENU_TABS_PART1						= "//div[contains(@class,'subMenu')]/a[text()='",
				SECURITY_QUESTION_UNDER_PREFERENCES					= "//td/a[text()='Security Question']",
				WEB_NOTIFICATION_FRAME								= "TB_iframeContent",
				ERROR_TITLE											= "emsErrorTitle",
				NOT_AUTHORIZED_TO_PERFORM_ACTION					= "//div[@class='emsLevel1']/b[text()='You are not authorized to perform this action.']",
				REGIONAL_ADMINISTRATOR_LINK							= "//div[@class='emsLevel2']/a",
				UNAUTHORIZED_ACESS_LOGGED							= "//div[@class='emsLevel2']",
				CLICK_HERE_TO_RETURN_TO_STATUS_VIEW					= "//div[@class='emsLevel3']/a[text()='Click here to return to the status view.']",
				EVENT_NOTIFICATION									= "//td/a[text()='Event Notification']",
				MY_EVENT_NOTIFICATION_PREFERENCES 					= "//h1[text()='My Event Notification Preferences']",
				EMAIL_ID_OF_EVENT_TEMPLATE 							= "/following-sibling::td/input[@name='eMailInd']",
				TEXT_PAGER_ID_OF_EVENT_TEMPLATE 					= "/following-sibling::td/input[@name='textPagerInd']",
				WEB_ID_OF_EVENT_TEMPLATE 							= "/following-sibling::td/input[@name='webInd']",
				MY_RESOURCE_ONLY_OF_EVENT_TEMPLATE 					= "/following-sibling::td/input[@name='myResourcesOnly']",
				TABLE_CELL_TEXT 									= "//td[text()='",
				MESSAGE_ON_MY_EVENT_NOTIFICATION_PREFERENCES_SCREEN	= "//div[@class='smallLeftMarginLabel']",
				SAVE 												= "input[value='Save']",
				SHOW_TABLE                                          = "//div[@id='link_show table']/a",
				EDIT_RESOURCE_DETAIL_VIEW_SECTIONS_SCREEN			= "//h1[text()='Edit Resource Detail View Sections']",
				EVENT_LIST 											= "//td/a[text()='Event List']",
				EVENT_LIST_PAGE 									= "//h1[text()='Event List']",
				MAP_PAGE											= "//h1[text()='Regional Map View']",
				APP_SWITCHER										= "//a[contains(@onclick,'SWITCH_APP')]",
				CUSTOM_VIEW_MAP_PAGE                                = "//div[@id='topSubNav']/h1[text()='Custom View - Map']",
				REGIONAL_INFO										= "//div/a[text()='Regional Info']",
				INSTANT_MESSAGING									= "//div[@id='topNav']/div/a[text()='IM']",
				STATUS_REPORTS										= "//tbody/tr/td/a[text()='Status Reports']";
	}
}
